/* MessageListBox.c generated by valac 0.56.3, the Vala compiler
 * generated from MessageListBox.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: nil; tab-width: 4 -*-*/
/*-
 * Copyright (c) 2017 elementary LLC. (https://elementary.io)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authored by: Corentin Noël <corentin@elementary.io>
 */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <camel/camel.h>
#include <gio/gio.h>
#include <glib/gi18n-lib.h>
#include <granite.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define MAIL_TYPE_MESSAGE_LIST_BOX (mail_message_list_box_get_type ())
#define MAIL_MESSAGE_LIST_BOX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MAIL_TYPE_MESSAGE_LIST_BOX, MailMessageListBox))
#define MAIL_MESSAGE_LIST_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MAIL_TYPE_MESSAGE_LIST_BOX, MailMessageListBoxClass))
#define MAIL_IS_MESSAGE_LIST_BOX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MAIL_TYPE_MESSAGE_LIST_BOX))
#define MAIL_IS_MESSAGE_LIST_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MAIL_TYPE_MESSAGE_LIST_BOX))
#define MAIL_MESSAGE_LIST_BOX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MAIL_TYPE_MESSAGE_LIST_BOX, MailMessageListBoxClass))

typedef struct _MailMessageListBox MailMessageListBox;
typedef struct _MailMessageListBoxClass MailMessageListBoxClass;
typedef struct _MailMessageListBoxPrivate MailMessageListBoxPrivate;
enum  {
	MAIL_MESSAGE_LIST_BOX_0_PROPERTY,
	MAIL_MESSAGE_LIST_BOX_CAN_REPLY_PROPERTY,
	MAIL_MESSAGE_LIST_BOX_CAN_MOVE_THREAD_PROPERTY,
	MAIL_MESSAGE_LIST_BOX_UIDS_PROPERTY,
	MAIL_MESSAGE_LIST_BOX_NUM_PROPERTIES
};
static GParamSpec* mail_message_list_box_properties[MAIL_MESSAGE_LIST_BOX_NUM_PROPERTIES];
#define _g_ptr_array_unref0(var) ((var == NULL) ? NULL : (var = (g_ptr_array_unref (var), NULL)))

#define MAIL_TYPE_MESSAGE_LIST_ITEM (mail_message_list_item_get_type ())
#define MAIL_MESSAGE_LIST_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MAIL_TYPE_MESSAGE_LIST_ITEM, MailMessageListItem))
#define MAIL_MESSAGE_LIST_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MAIL_TYPE_MESSAGE_LIST_ITEM, MailMessageListItemClass))
#define MAIL_IS_MESSAGE_LIST_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MAIL_TYPE_MESSAGE_LIST_ITEM))
#define MAIL_IS_MESSAGE_LIST_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MAIL_TYPE_MESSAGE_LIST_ITEM))
#define MAIL_MESSAGE_LIST_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MAIL_TYPE_MESSAGE_LIST_ITEM, MailMessageListItemClass))

typedef struct _MailMessageListItem MailMessageListItem;
typedef struct _MailMessageListItemClass MailMessageListItemClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef enum  {
	MAIL_COMPOSER_WIDGET_TYPE_REPLY,
	MAIL_COMPOSER_WIDGET_TYPE_REPLY_ALL,
	MAIL_COMPOSER_WIDGET_TYPE_FORWARD,
	MAIL_COMPOSER_WIDGET_TYPE_DRAFT
} MailComposerWidgetType;

#define MAIL_COMPOSER_WIDGET_TYPE_TYPE (mail_composer_widget_type_get_type ())

#define MAIL_TYPE_INLINE_COMPOSER (mail_inline_composer_get_type ())
#define MAIL_INLINE_COMPOSER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MAIL_TYPE_INLINE_COMPOSER, MailInlineComposer))
#define MAIL_INLINE_COMPOSER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MAIL_TYPE_INLINE_COMPOSER, MailInlineComposerClass))
#define MAIL_IS_INLINE_COMPOSER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MAIL_TYPE_INLINE_COMPOSER))
#define MAIL_IS_INLINE_COMPOSER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MAIL_TYPE_INLINE_COMPOSER))
#define MAIL_INLINE_COMPOSER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MAIL_TYPE_INLINE_COMPOSER, MailInlineComposerClass))

typedef struct _MailInlineComposer MailInlineComposer;
typedef struct _MailInlineComposerClass MailInlineComposerClass;
typedef struct _Block30Data Block30Data;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _MailMessageListBoxAddInlineComposerData MailMessageListBoxAddInlineComposerData;
enum  {
	MAIL_MESSAGE_LIST_BOX_HOVERING_OVER_LINK_SIGNAL,
	MAIL_MESSAGE_LIST_BOX_NUM_SIGNALS
};
static guint mail_message_list_box_signals[MAIL_MESSAGE_LIST_BOX_NUM_SIGNALS] = {0};

struct _MailMessageListBox {
	GtkListBox parent_instance;
	MailMessageListBoxPrivate * priv;
};

struct _MailMessageListBoxClass {
	GtkListBoxClass parent_class;
};

struct _MailMessageListBoxPrivate {
	gboolean _can_reply;
	gboolean _can_move_thread;
	GPtrArray* _uids;
};

struct _Block30Data {
	int _ref_count_;
	MailMessageListBox* self;
	MailInlineComposer* composer;
	gpointer _async_data_;
};

struct _MailMessageListBoxAddInlineComposerData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	MailMessageListBox* self;
	MailComposerWidgetType type;
	MailMessageListItem* message_item;
	Block30Data* _data30_;
	GtkListBoxRow* last_child;
	GList* _tmp0_;
	GList* _tmp1_;
	GtkListBoxRow* _tmp2_;
	GtkListBoxRow* _tmp3_;
	GtkListBoxRow* _tmp4_;
	gboolean _tmp5_;
	GtkListBoxRow* _tmp6_;
	GtkListBoxRow* _tmp7_;
	GtkListBoxRow* _tmp8_;
	gchar* content_to_quote;
	gchar* _tmp10_;
	CamelMimeMessage* mime_message;
	CamelMessageInfo* message_info;
	gchar* _tmp11_;
	CamelMimeMessage* _tmp12_;
	CamelMimeMessage* _tmp13_;
	CamelMimeMessage* _tmp14_;
	CamelMessageInfo* _tmp15_;
	CamelMessageInfo* _tmp16_;
	CamelMessageInfo* _tmp17_;
	CamelMessageInfo* _tmp18_;
	CamelMimeMessage* _tmp19_;
	const gchar* _tmp20_;
	MailInlineComposer* _tmp21_;
	MailInlineComposer* _tmp22_;
	MailInlineComposer* _tmp23_;
};

static gint MailMessageListBox_private_offset;
static gpointer mail_message_list_box_parent_class = NULL;

VALA_EXTERN GType mail_message_list_box_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (MailMessageListBox, g_object_unref)
static void _g_free0_ (gpointer var);
VALA_EXTERN MailMessageListBox* mail_message_list_box_new (void);
VALA_EXTERN MailMessageListBox* mail_message_list_box_construct (GType object_type);
VALA_EXTERN void mail_message_list_box_set_conversation (MailMessageListBox* self,
                                             CamelFolderThreadNode* node);
VALA_EXTERN void mail_message_list_box_set_can_reply (MailMessageListBox* self,
                                          gboolean value);
VALA_EXTERN void mail_message_list_box_set_can_move_thread (MailMessageListBox* self,
                                                gboolean value);
static void __lambda38_ (MailMessageListBox* self,
                  GtkWidget* child);
static void ___lambda38__gfunc (gconstpointer data,
                         gpointer self);
static void mail_message_list_box_set_uids (MailMessageListBox* self,
                                     GPtrArray* value);
VALA_EXTERN GType mail_message_list_item_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (MailMessageListItem, g_object_unref)
VALA_EXTERN MailMessageListItem* mail_message_list_item_new (CamelMessageInfo* message_info);
VALA_EXTERN MailMessageListItem* mail_message_list_item_construct (GType object_type,
                                                       CamelMessageInfo* message_info);
VALA_EXTERN GPtrArray* mail_message_list_box_get_uids (MailMessageListBox* self);
static void mail_message_list_box_go_down (MailMessageListBox* self,
                                    CamelFolderThreadNode* node);
VALA_EXTERN void mail_message_list_item_set_expanded (MailMessageListItem* self,
                                          gboolean value);
static void mail_message_list_box_add_inline_composer_data_free (gpointer _data);
VALA_EXTERN GType mail_composer_widget_type_get_type (void) G_GNUC_CONST ;
VALA_EXTERN void mail_message_list_box_add_inline_composer (MailMessageListBox* self,
                                                MailComposerWidgetType type,
                                                MailMessageListItem* message_item,
                                                GAsyncReadyCallback _callback_,
                                                gpointer _user_data_);
VALA_EXTERN void mail_message_list_box_add_inline_composer_finish (MailMessageListBox* self,
                                                       GAsyncResult* _res_);
static gboolean mail_message_list_box_add_inline_composer_co (MailMessageListBoxAddInlineComposerData* _data_);
VALA_EXTERN GType mail_inline_composer_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (MailInlineComposer, g_object_unref)
static Block30Data* block30_data_ref (Block30Data* _data30_);
static void block30_data_unref (void * _userdata_);
VALA_EXTERN void mail_message_list_item_get_message_body_html (MailMessageListItem* self,
                                                   GAsyncReadyCallback _callback_,
                                                   gpointer _user_data_);
VALA_EXTERN gchar* mail_message_list_item_get_message_body_html_finish (MailMessageListItem* self,
                                                            GAsyncResult* _res_);
static void mail_message_list_box_add_inline_composer_ready (GObject* source_object,
                                                      GAsyncResult* _res_,
                                                      gpointer _user_data_);
VALA_EXTERN CamelMimeMessage* mail_message_list_item_get_mime_message (MailMessageListItem* self);
VALA_EXTERN CamelMessageInfo* mail_message_list_item_get_message_info (MailMessageListItem* self);
VALA_EXTERN MailInlineComposer* mail_inline_composer_new (MailComposerWidgetType type,
                                              CamelMessageInfo* info,
                                              CamelMimeMessage* message,
                                              const gchar* content);
VALA_EXTERN MailInlineComposer* mail_inline_composer_construct (GType object_type,
                                                    MailComposerWidgetType type,
                                                    CamelMessageInfo* info,
                                                    CamelMimeMessage* message,
                                                    const gchar* content);
static void __lambda80_ (Block30Data* _data30_);
static void ___lambda80__mail_inline_composer_discarded (MailInlineComposer* _sender,
                                                  gpointer self);
static gint mail_message_list_box_message_sort_function (GtkListBoxRow* item1,
                                                  GtkListBoxRow* item2);
VALA_EXTERN gboolean mail_message_list_box_get_can_reply (MailMessageListBox* self);
VALA_EXTERN gboolean mail_message_list_box_get_can_move_thread (MailMessageListBox* self);
static void g_cclosure_user_marshal_VOID__STRING_STRING (GClosure * closure,
                                                  GValue * return_value,
                                                  guint n_param_values,
                                                  const GValue * param_values,
                                                  gpointer invocation_hint,
                                                  gpointer marshal_data);
static GObject * mail_message_list_box_constructor (GType type,
                                             guint n_construct_properties,
                                             GObjectConstructParam * construct_properties);
static gint _mail_message_list_box_message_sort_function_gtk_list_box_sort_func (GtkListBoxRow* row1,
                                                                          GtkListBoxRow* row2,
                                                                          gpointer self);
static void mail_message_list_box_finalize (GObject * obj);
static GType mail_message_list_box_get_type_once (void);
static void _vala_mail_message_list_box_get_property (GObject * object,
                                               guint property_id,
                                               GValue * value,
                                               GParamSpec * pspec);
static void _vala_mail_message_list_box_set_property (GObject * object,
                                               guint property_id,
                                               const GValue * value,
                                               GParamSpec * pspec);

static inline gpointer
mail_message_list_box_get_instance_private (MailMessageListBox* self)
{
	return G_STRUCT_MEMBER_P (self, MailMessageListBox_private_offset);
}

static void
_g_free0_ (gpointer var)
{
	var = (g_free (var), NULL);
}

MailMessageListBox*
mail_message_list_box_construct (GType object_type)
{
	MailMessageListBox * self = NULL;
	self = (MailMessageListBox*) g_object_new (object_type, "selection-mode", GTK_SELECTION_NONE, NULL);
	return self;
}

MailMessageListBox*
mail_message_list_box_new (void)
{
	return mail_message_list_box_construct (MAIL_TYPE_MESSAGE_LIST_BOX);
}

static void
__lambda38_ (MailMessageListBox* self,
             GtkWidget* child)
{
	g_return_if_fail (child != NULL);
	gtk_widget_destroy (child);
}

static void
___lambda38__gfunc (gconstpointer data,
                    gpointer self)
{
	__lambda38_ ((MailMessageListBox*) self, (GtkWidget*) data);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

void
mail_message_list_box_set_conversation (MailMessageListBox* self,
                                        CamelFolderThreadNode* node)
{
	GList* _tmp0_;
	GList* _tmp1_;
	GPtrArray* _tmp2_;
	GPtrArray* _tmp3_;
	MailMessageListItem* item = NULL;
	CamelMessageInfo* _tmp4_;
	MailMessageListItem* _tmp5_;
	MailMessageListItem* _tmp6_;
	GPtrArray* _tmp7_;
	CamelMessageInfo* _tmp8_;
	const gchar* _tmp9_;
	const gchar* _tmp10_;
	gchar* _tmp11_;
	CamelFolderThreadNode* _tmp12_;
	GList* children = NULL;
	GList* _tmp14_;
	guint num_children = 0U;
	GList* _tmp15_;
	g_return_if_fail (self != NULL);
	mail_message_list_box_set_can_reply (self, FALSE);
	mail_message_list_box_set_can_move_thread (self, FALSE);
	_tmp0_ = gtk_container_get_children ((GtkContainer*) self);
	_tmp1_ = _tmp0_;
	g_list_foreach (_tmp1_, ___lambda38__gfunc, self);
	(_tmp1_ == NULL) ? NULL : (_tmp1_ = (g_list_free (_tmp1_), NULL));
	_tmp2_ = g_ptr_array_new_full ((guint) 0, _g_free0_);
	_tmp3_ = _tmp2_;
	mail_message_list_box_set_uids (self, _tmp3_);
	_g_ptr_array_unref0 (_tmp3_);
	if (node == NULL) {
		return;
	}
	mail_message_list_box_set_can_move_thread (self, TRUE);
	_tmp4_ = node->message;
	_tmp5_ = mail_message_list_item_new (_tmp4_);
	g_object_ref_sink (_tmp5_);
	item = _tmp5_;
	_tmp6_ = item;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp6_);
	_tmp7_ = self->priv->_uids;
	_tmp8_ = node->message;
	_tmp9_ = camel_message_info_get_uid (_tmp8_);
	_tmp10_ = _tmp9_;
	_tmp11_ = g_strdup (_tmp10_);
	g_ptr_array_add (_tmp7_, _tmp11_);
	_tmp12_ = node->child;
	if (_tmp12_ != NULL) {
		CamelFolderThreadNode* _tmp13_;
		_tmp13_ = node->child;
		mail_message_list_box_go_down (self, (CamelFolderThreadNode*) _tmp13_);
	}
	_tmp14_ = gtk_container_get_children ((GtkContainer*) self);
	children = _tmp14_;
	_tmp15_ = children;
	num_children = g_list_length (_tmp15_);
	if (num_children > ((guint) 0)) {
		GtkListBoxRow* child = NULL;
		GtkListBoxRow* _tmp16_;
		GtkListBoxRow* _tmp17_;
		gboolean _tmp18_ = FALSE;
		GtkListBoxRow* _tmp19_;
		_tmp16_ = gtk_list_box_get_row_at_index ((GtkListBox*) self, ((gint) num_children) - 1);
		_tmp17_ = _g_object_ref0 (_tmp16_);
		child = _tmp17_;
		_tmp19_ = child;
		if (_tmp19_ != NULL) {
			GtkListBoxRow* _tmp20_;
			_tmp20_ = child;
			_tmp18_ = MAIL_IS_MESSAGE_LIST_ITEM (_tmp20_);
		} else {
			_tmp18_ = FALSE;
		}
		if (_tmp18_) {
			MailMessageListItem* list_item = NULL;
			GtkListBoxRow* _tmp21_;
			MailMessageListItem* _tmp22_;
			MailMessageListItem* _tmp23_;
			MailMessageListItem* _tmp24_;
			_tmp21_ = child;
			_tmp22_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp21_, MAIL_TYPE_MESSAGE_LIST_ITEM, MailMessageListItem));
			list_item = _tmp22_;
			_tmp23_ = list_item;
			mail_message_list_item_set_expanded (_tmp23_, TRUE);
			_tmp24_ = list_item;
			g_object_bind_property_with_closures ((GObject*) _tmp24_, "loaded", (GObject*) self, "can-reply", G_BINDING_SYNC_CREATE, (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, (GClosureNotify) NULL)), (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, (GClosureNotify) NULL)));
			_g_object_unref0 (list_item);
		}
		_g_object_unref0 (child);
	}
	(children == NULL) ? NULL : (children = (g_list_free (children), NULL));
	_g_object_unref0 (item);
}

static void
mail_message_list_box_go_down (MailMessageListBox* self,
                               CamelFolderThreadNode* node)
{
	CamelFolderThreadNode* current_node = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (node != NULL);
	current_node = node;
	while (TRUE) {
		CamelFolderThreadNode* _tmp0_;
		MailMessageListItem* item = NULL;
		CamelFolderThreadNode* _tmp1_;
		CamelMessageInfo* _tmp2_;
		MailMessageListItem* _tmp3_;
		MailMessageListItem* _tmp4_;
		GPtrArray* _tmp5_;
		CamelFolderThreadNode* _tmp6_;
		CamelMessageInfo* _tmp7_;
		const gchar* _tmp8_;
		const gchar* _tmp9_;
		gchar* _tmp10_;
		CamelFolderThreadNode* _tmp11_;
		CamelFolderThreadNode* _tmp12_;
		CamelFolderThreadNode* _tmp15_;
		CamelFolderThreadNode* _tmp16_;
		_tmp0_ = current_node;
		if (!(_tmp0_ != NULL)) {
			break;
		}
		_tmp1_ = current_node;
		_tmp2_ = _tmp1_->message;
		_tmp3_ = mail_message_list_item_new (_tmp2_);
		g_object_ref_sink (_tmp3_);
		item = _tmp3_;
		_tmp4_ = item;
		gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp4_);
		_tmp5_ = self->priv->_uids;
		_tmp6_ = current_node;
		_tmp7_ = _tmp6_->message;
		_tmp8_ = camel_message_info_get_uid (_tmp7_);
		_tmp9_ = _tmp8_;
		_tmp10_ = g_strdup (_tmp9_);
		g_ptr_array_add (_tmp5_, _tmp10_);
		_tmp11_ = current_node;
		_tmp12_ = _tmp11_->next;
		if (_tmp12_ != NULL) {
			CamelFolderThreadNode* _tmp13_;
			CamelFolderThreadNode* _tmp14_;
			_tmp13_ = current_node;
			_tmp14_ = _tmp13_->next;
			mail_message_list_box_go_down (self, (CamelFolderThreadNode*) _tmp14_);
		}
		_tmp15_ = current_node;
		_tmp16_ = _tmp15_->child;
		current_node = (CamelFolderThreadNode*) _tmp16_;
		_g_object_unref0 (item);
	}
}

static void
mail_message_list_box_add_inline_composer_data_free (gpointer _data)
{
	MailMessageListBoxAddInlineComposerData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->message_item);
	_g_object_unref0 (_data_->self);
	g_slice_free (MailMessageListBoxAddInlineComposerData, _data_);
}

void
mail_message_list_box_add_inline_composer (MailMessageListBox* self,
                                           MailComposerWidgetType type,
                                           MailMessageListItem* message_item,
                                           GAsyncReadyCallback _callback_,
                                           gpointer _user_data_)
{
	MailMessageListBoxAddInlineComposerData* _data_;
	MailMessageListBox* _tmp0_;
	MailMessageListItem* _tmp1_;
	g_return_if_fail (self != NULL);
	_data_ = g_slice_new0 (MailMessageListBoxAddInlineComposerData);
	_data_->_async_result = g_task_new (G_OBJECT (self), NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, mail_message_list_box_add_inline_composer_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	_data_->type = type;
	_tmp1_ = _g_object_ref0 (message_item);
	_g_object_unref0 (_data_->message_item);
	_data_->message_item = _tmp1_;
	mail_message_list_box_add_inline_composer_co (_data_);
}

void
mail_message_list_box_add_inline_composer_finish (MailMessageListBox* self,
                                                  GAsyncResult* _res_)
{
	MailMessageListBoxAddInlineComposerData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
}

static Block30Data*
block30_data_ref (Block30Data* _data30_)
{
	g_atomic_int_inc (&_data30_->_ref_count_);
	return _data30_;
}

static void
block30_data_unref (void * _userdata_)
{
	Block30Data* _data30_;
	_data30_ = (Block30Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data30_->_ref_count_)) {
		MailMessageListBox* self;
		self = _data30_->self;
		_g_object_unref0 (_data30_->composer);
		_g_object_unref0 (self);
		g_slice_free (Block30Data, _data30_);
	}
}

static void
mail_message_list_box_add_inline_composer_ready (GObject* source_object,
                                                 GAsyncResult* _res_,
                                                 gpointer _user_data_)
{
	MailMessageListBoxAddInlineComposerData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	mail_message_list_box_add_inline_composer_co (_data_);
}

static void
__lambda80_ (Block30Data* _data30_)
{
	MailMessageListBox* self;
	MailInlineComposer* _tmp0_;
	MailInlineComposer* _tmp1_;
	self = _data30_->self;
	mail_message_list_box_set_can_reply (self, TRUE);
	mail_message_list_box_set_can_move_thread (self, TRUE);
	_tmp0_ = _data30_->composer;
	gtk_container_remove ((GtkContainer*) self, (GtkWidget*) _tmp0_);
	_tmp1_ = _data30_->composer;
	gtk_widget_destroy ((GtkWidget*) _tmp1_);
}

static void
___lambda80__mail_inline_composer_discarded (MailInlineComposer* _sender,
                                             gpointer self)
{
	__lambda80_ (self);
}

static gboolean
mail_message_list_box_add_inline_composer_co (MailMessageListBoxAddInlineComposerData* _data_)
{
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_data30_ = g_slice_new0 (Block30Data);
	_data_->_data30_->_ref_count_ = 1;
	_data_->_data30_->self = g_object_ref (_data_->self);
	_data_->_data30_->_async_data_ = _data_;
	_data_->_tmp0_ = gtk_container_get_children ((GtkContainer*) _data_->self);
	_data_->_tmp1_ = _data_->_tmp0_;
	_data_->_tmp2_ = gtk_list_box_get_row_at_index ((GtkListBox*) _data_->self, ((gint) g_list_length (_data_->_tmp1_)) - 1);
	_data_->_tmp3_ = _g_object_ref0 (_data_->_tmp2_);
	_data_->_tmp4_ = _data_->_tmp3_;
	(_data_->_tmp1_ == NULL) ? NULL : (_data_->_tmp1_ = (g_list_free (_data_->_tmp1_), NULL));
	_data_->last_child = _data_->_tmp4_;
	_data_->_tmp6_ = _data_->last_child;
	if (_data_->_tmp6_ == NULL) {
		_data_->_tmp5_ = TRUE;
	} else {
		_data_->_tmp7_ = _data_->last_child;
		_data_->_tmp5_ = MAIL_IS_INLINE_COMPOSER (_data_->_tmp7_);
	}
	if (_data_->_tmp5_) {
		_g_object_unref0 (_data_->last_child);
		block30_data_unref (_data_->_data30_);
		_data_->_data30_ = NULL;
		g_task_return_pointer (_data_->_async_result, _data_, NULL);
		if (_data_->_state_ != 0) {
			while (!g_task_get_completed (_data_->_async_result)) {
				g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
			}
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	if (_data_->message_item == NULL) {
		MailMessageListItem* _tmp9_;
		_data_->_tmp8_ = _data_->last_child;
		_tmp9_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_data_->_tmp8_, MAIL_TYPE_MESSAGE_LIST_ITEM, MailMessageListItem));
		_g_object_unref0 (_data_->message_item);
		_data_->message_item = _tmp9_;
	}
	_data_->_tmp10_ = g_strdup ("");
	_data_->content_to_quote = _data_->_tmp10_;
	_data_->mime_message = NULL;
	_data_->message_info = NULL;
	_data_->_state_ = 1;
	mail_message_list_item_get_message_body_html (_data_->message_item, mail_message_list_box_add_inline_composer_ready, _data_);
	return FALSE;
	_state_1:
	_data_->_tmp11_ = mail_message_list_item_get_message_body_html_finish (_data_->message_item, _data_->_res_);
	_g_free0 (_data_->content_to_quote);
	_data_->content_to_quote = _data_->_tmp11_;
	_data_->_tmp12_ = mail_message_list_item_get_mime_message (_data_->message_item);
	_data_->_tmp13_ = _data_->_tmp12_;
	_data_->_tmp14_ = _g_object_ref0 (_data_->_tmp13_);
	_g_object_unref0 (_data_->mime_message);
	_data_->mime_message = _data_->_tmp14_;
	_data_->_tmp15_ = mail_message_list_item_get_message_info (_data_->message_item);
	_data_->_tmp16_ = _data_->_tmp15_;
	_data_->_tmp17_ = _g_object_ref0 (_data_->_tmp16_);
	_g_object_unref0 (_data_->message_info);
	_data_->message_info = _data_->_tmp17_;
	_data_->_tmp18_ = _data_->message_info;
	_data_->_tmp19_ = _data_->mime_message;
	_data_->_tmp20_ = _data_->content_to_quote;
	_data_->_tmp21_ = mail_inline_composer_new (_data_->type, _data_->_tmp18_, _data_->_tmp19_, _data_->_tmp20_);
	g_object_ref_sink (_data_->_tmp21_);
	_data_->_data30_->composer = _data_->_tmp21_;
	_data_->_tmp22_ = _data_->_data30_->composer;
	g_signal_connect_data (_data_->_tmp22_, "discarded", (GCallback) ___lambda80__mail_inline_composer_discarded, block30_data_ref (_data_->_data30_), (GClosureNotify) block30_data_unref, 0);
	_data_->_tmp23_ = _data_->_data30_->composer;
	gtk_container_add ((GtkContainer*) _data_->self, (GtkWidget*) _data_->_tmp23_);
	mail_message_list_box_set_can_reply (_data_->self, FALSE);
	mail_message_list_box_set_can_move_thread (_data_->self, TRUE);
	_g_object_unref0 (_data_->message_info);
	_g_object_unref0 (_data_->mime_message);
	_g_free0 (_data_->content_to_quote);
	_g_object_unref0 (_data_->last_child);
	block30_data_unref (_data_->_data30_);
	_data_->_data30_ = NULL;
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
	if (_data_->_state_ != 0) {
		while (!g_task_get_completed (_data_->_async_result)) {
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
		}
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}

static gint
mail_message_list_box_message_sort_function (GtkListBoxRow* item1,
                                             GtkListBoxRow* item2)
{
	MailMessageListItem* message1 = NULL;
	MailMessageListItem* message2 = NULL;
	gint64 timestamp1 = 0LL;
	MailMessageListItem* _tmp0_;
	CamelMessageInfo* _tmp1_;
	CamelMessageInfo* _tmp2_;
	gint64 _tmp3_;
	gint64 _tmp4_;
	gint64 timestamp2 = 0LL;
	MailMessageListItem* _tmp10_;
	CamelMessageInfo* _tmp11_;
	CamelMessageInfo* _tmp12_;
	gint64 _tmp13_;
	gint64 _tmp14_;
	gint result;
	g_return_val_if_fail (item1 != NULL, 0);
	g_return_val_if_fail (item2 != NULL, 0);
	message1 = G_TYPE_CHECK_INSTANCE_CAST (item1, MAIL_TYPE_MESSAGE_LIST_ITEM, MailMessageListItem);
	message2 = G_TYPE_CHECK_INSTANCE_CAST (item2, MAIL_TYPE_MESSAGE_LIST_ITEM, MailMessageListItem);
	_tmp0_ = message1;
	_tmp1_ = mail_message_list_item_get_message_info (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = camel_message_info_get_date_received (_tmp2_);
	_tmp4_ = _tmp3_;
	timestamp1 = _tmp4_;
	if (timestamp1 == ((gint64) 0)) {
		MailMessageListItem* _tmp5_;
		CamelMessageInfo* _tmp6_;
		CamelMessageInfo* _tmp7_;
		gint64 _tmp8_;
		gint64 _tmp9_;
		_tmp5_ = message1;
		_tmp6_ = mail_message_list_item_get_message_info (_tmp5_);
		_tmp7_ = _tmp6_;
		_tmp8_ = camel_message_info_get_date_sent (_tmp7_);
		_tmp9_ = _tmp8_;
		timestamp1 = _tmp9_;
	}
	_tmp10_ = message2;
	_tmp11_ = mail_message_list_item_get_message_info (_tmp10_);
	_tmp12_ = _tmp11_;
	_tmp13_ = camel_message_info_get_date_received (_tmp12_);
	_tmp14_ = _tmp13_;
	timestamp2 = _tmp14_;
	if (timestamp2 == ((gint64) 0)) {
		MailMessageListItem* _tmp15_;
		CamelMessageInfo* _tmp16_;
		CamelMessageInfo* _tmp17_;
		gint64 _tmp18_;
		gint64 _tmp19_;
		_tmp15_ = message2;
		_tmp16_ = mail_message_list_item_get_message_info (_tmp15_);
		_tmp17_ = _tmp16_;
		_tmp18_ = camel_message_info_get_date_sent (_tmp17_);
		_tmp19_ = _tmp18_;
		timestamp2 = _tmp19_;
	}
	result = (gint) (timestamp1 - timestamp2);
	return result;
}

gboolean
mail_message_list_box_get_can_reply (MailMessageListBox* self)
{
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_can_reply;
	return result;
}

void
mail_message_list_box_set_can_reply (MailMessageListBox* self,
                                     gboolean value)
{
	gboolean old_value;
	g_return_if_fail (self != NULL);
	old_value = mail_message_list_box_get_can_reply (self);
	if (old_value != value) {
		self->priv->_can_reply = value;
		g_object_notify_by_pspec ((GObject *) self, mail_message_list_box_properties[MAIL_MESSAGE_LIST_BOX_CAN_REPLY_PROPERTY]);
	}
}

gboolean
mail_message_list_box_get_can_move_thread (MailMessageListBox* self)
{
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_can_move_thread;
	return result;
}

void
mail_message_list_box_set_can_move_thread (MailMessageListBox* self,
                                           gboolean value)
{
	gboolean old_value;
	g_return_if_fail (self != NULL);
	old_value = mail_message_list_box_get_can_move_thread (self);
	if (old_value != value) {
		self->priv->_can_move_thread = value;
		g_object_notify_by_pspec ((GObject *) self, mail_message_list_box_properties[MAIL_MESSAGE_LIST_BOX_CAN_MOVE_THREAD_PROPERTY]);
	}
}

GPtrArray*
mail_message_list_box_get_uids (MailMessageListBox* self)
{
	GPtrArray* result;
	GPtrArray* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_uids;
	result = _tmp0_;
	return result;
}

static gpointer
_g_ptr_array_ref0 (gpointer self)
{
	return self ? g_ptr_array_ref (self) : NULL;
}

static void
mail_message_list_box_set_uids (MailMessageListBox* self,
                                GPtrArray* value)
{
	GPtrArray* old_value;
	g_return_if_fail (self != NULL);
	old_value = mail_message_list_box_get_uids (self);
	if (old_value != value) {
		GPtrArray* _tmp0_;
		_tmp0_ = _g_ptr_array_ref0 (value);
		_g_ptr_array_unref0 (self->priv->_uids);
		self->priv->_uids = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, mail_message_list_box_properties[MAIL_MESSAGE_LIST_BOX_UIDS_PROPERTY]);
	}
}

static void
g_cclosure_user_marshal_VOID__STRING_STRING (GClosure * closure,
                                             GValue * return_value,
                                             guint n_param_values,
                                             const GValue * param_values,
                                             gpointer invocation_hint,
                                             gpointer marshal_data)
{
	typedef void (*GMarshalFunc_VOID__STRING_STRING) (gpointer data1, const char* arg_1, const char* arg_2, gpointer data2);
	register GMarshalFunc_VOID__STRING_STRING callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 3);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__STRING_STRING) (marshal_data ? marshal_data : cc->callback);
	callback (data1, g_value_get_string (param_values + 1), g_value_get_string (param_values + 2), data2);
}

static gint
_mail_message_list_box_message_sort_function_gtk_list_box_sort_func (GtkListBoxRow* row1,
                                                                     GtkListBoxRow* row2,
                                                                     gpointer self)
{
	gint result;
	result = mail_message_list_box_message_sort_function (row1, row2);
	return result;
}

static GObject *
mail_message_list_box_constructor (GType type,
                                   guint n_construct_properties,
                                   GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	MailMessageListBox * self;
	GtkLabel* placeholder = NULL;
	GtkLabel* _tmp0_;
	GtkLabel* _tmp1_;
	GtkStyleContext* placeholder_style_context = NULL;
	GtkLabel* _tmp2_;
	GtkStyleContext* _tmp3_;
	GtkStyleContext* _tmp4_;
	GtkStyleContext* _tmp5_;
	GtkStyleContext* _tmp6_;
	GtkStyleContext* _tmp7_;
	GtkLabel* _tmp8_;
	parent_class = G_OBJECT_CLASS (mail_message_list_box_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MAIL_TYPE_MESSAGE_LIST_BOX, MailMessageListBox);
	_tmp0_ = (GtkLabel*) gtk_label_new (_ ("No Message Selected"));
	g_object_ref_sink (_tmp0_);
	placeholder = _tmp0_;
	_tmp1_ = placeholder;
	gtk_widget_set_visible ((GtkWidget*) _tmp1_, TRUE);
	_tmp2_ = placeholder;
	_tmp3_ = gtk_widget_get_style_context ((GtkWidget*) _tmp2_);
	_tmp4_ = _g_object_ref0 (_tmp3_);
	placeholder_style_context = _tmp4_;
	_tmp5_ = placeholder_style_context;
	gtk_style_context_add_class (_tmp5_, GRANITE_STYLE_CLASS_H2_LABEL);
	_tmp6_ = placeholder_style_context;
	gtk_style_context_add_class (_tmp6_, GTK_STYLE_CLASS_DIM_LABEL);
	_tmp7_ = gtk_widget_get_style_context ((GtkWidget*) self);
	gtk_style_context_add_class (_tmp7_, GTK_STYLE_CLASS_BACKGROUND);
	_tmp8_ = placeholder;
	gtk_list_box_set_placeholder ((GtkListBox*) self, (GtkWidget*) _tmp8_);
	gtk_list_box_set_sort_func ((GtkListBox*) self, _mail_message_list_box_message_sort_function_gtk_list_box_sort_func, NULL, NULL);
	_g_object_unref0 (placeholder_style_context);
	_g_object_unref0 (placeholder);
	return obj;
}

static void
mail_message_list_box_class_init (MailMessageListBoxClass * klass,
                                  gpointer klass_data)
{
	mail_message_list_box_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &MailMessageListBox_private_offset);
	G_OBJECT_CLASS (klass)->get_property = _vala_mail_message_list_box_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_mail_message_list_box_set_property;
	G_OBJECT_CLASS (klass)->constructor = mail_message_list_box_constructor;
	G_OBJECT_CLASS (klass)->finalize = mail_message_list_box_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), MAIL_MESSAGE_LIST_BOX_CAN_REPLY_PROPERTY, mail_message_list_box_properties[MAIL_MESSAGE_LIST_BOX_CAN_REPLY_PROPERTY] = g_param_spec_boolean ("can-reply", "can-reply", "can-reply", FALSE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MAIL_MESSAGE_LIST_BOX_CAN_MOVE_THREAD_PROPERTY, mail_message_list_box_properties[MAIL_MESSAGE_LIST_BOX_CAN_MOVE_THREAD_PROPERTY] = g_param_spec_boolean ("can-move-thread", "can-move-thread", "can-move-thread", FALSE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MAIL_MESSAGE_LIST_BOX_UIDS_PROPERTY, mail_message_list_box_properties[MAIL_MESSAGE_LIST_BOX_UIDS_PROPERTY] = g_param_spec_boxed ("uids", "uids", "uids", G_TYPE_PTR_ARRAY, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
	mail_message_list_box_signals[MAIL_MESSAGE_LIST_BOX_HOVERING_OVER_LINK_SIGNAL] = g_signal_new ("hovering-over-link", MAIL_TYPE_MESSAGE_LIST_BOX, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__STRING_STRING, G_TYPE_NONE, 2, G_TYPE_STRING, G_TYPE_STRING);
}

static void
mail_message_list_box_instance_init (MailMessageListBox * self,
                                     gpointer klass)
{
	GPtrArray* _tmp0_;
	self->priv = mail_message_list_box_get_instance_private (self);
	self->priv->_can_reply = FALSE;
	self->priv->_can_move_thread = FALSE;
	_tmp0_ = g_ptr_array_new_full ((guint) 0, _g_free0_);
	self->priv->_uids = _tmp0_;
}

static void
mail_message_list_box_finalize (GObject * obj)
{
	MailMessageListBox * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MAIL_TYPE_MESSAGE_LIST_BOX, MailMessageListBox);
	_g_ptr_array_unref0 (self->priv->_uids);
	G_OBJECT_CLASS (mail_message_list_box_parent_class)->finalize (obj);
}

static GType
mail_message_list_box_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (MailMessageListBoxClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) mail_message_list_box_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MailMessageListBox), 0, (GInstanceInitFunc) mail_message_list_box_instance_init, NULL };
	GType mail_message_list_box_type_id;
	mail_message_list_box_type_id = g_type_register_static (gtk_list_box_get_type (), "MailMessageListBox", &g_define_type_info, 0);
	MailMessageListBox_private_offset = g_type_add_instance_private (mail_message_list_box_type_id, sizeof (MailMessageListBoxPrivate));
	return mail_message_list_box_type_id;
}

GType
mail_message_list_box_get_type (void)
{
	static volatile gsize mail_message_list_box_type_id__once = 0;
	if (g_once_init_enter (&mail_message_list_box_type_id__once)) {
		GType mail_message_list_box_type_id;
		mail_message_list_box_type_id = mail_message_list_box_get_type_once ();
		g_once_init_leave (&mail_message_list_box_type_id__once, mail_message_list_box_type_id);
	}
	return mail_message_list_box_type_id__once;
}

static void
_vala_mail_message_list_box_get_property (GObject * object,
                                          guint property_id,
                                          GValue * value,
                                          GParamSpec * pspec)
{
	MailMessageListBox * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, MAIL_TYPE_MESSAGE_LIST_BOX, MailMessageListBox);
	switch (property_id) {
		case MAIL_MESSAGE_LIST_BOX_CAN_REPLY_PROPERTY:
		g_value_set_boolean (value, mail_message_list_box_get_can_reply (self));
		break;
		case MAIL_MESSAGE_LIST_BOX_CAN_MOVE_THREAD_PROPERTY:
		g_value_set_boolean (value, mail_message_list_box_get_can_move_thread (self));
		break;
		case MAIL_MESSAGE_LIST_BOX_UIDS_PROPERTY:
		g_value_set_boxed (value, mail_message_list_box_get_uids (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_mail_message_list_box_set_property (GObject * object,
                                          guint property_id,
                                          const GValue * value,
                                          GParamSpec * pspec)
{
	MailMessageListBox * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, MAIL_TYPE_MESSAGE_LIST_BOX, MailMessageListBox);
	switch (property_id) {
		case MAIL_MESSAGE_LIST_BOX_CAN_REPLY_PROPERTY:
		mail_message_list_box_set_can_reply (self, g_value_get_boolean (value));
		break;
		case MAIL_MESSAGE_LIST_BOX_CAN_MOVE_THREAD_PROPERTY:
		mail_message_list_box_set_can_move_thread (self, g_value_get_boolean (value));
		break;
		case MAIL_MESSAGE_LIST_BOX_UIDS_PROPERTY:
		mail_message_list_box_set_uids (self, g_value_get_boxed (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

