/* Application.c generated by valac 0.56.3, the Vala compiler
 * generated from Application.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: nil; tab-width: 4 -*-*/
/*-
 * Copyright (c) 2017 elementary LLC. (https://elementary.io)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authored by: Corentin Noël <corentin@elementary.io>
 */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <glib.h>
#include <handy.h>
#include <stdlib.h>
#include <string.h>
#include <granite.h>
#include <gdk/gdk.h>
#include <locale.h>
#include <glib/gi18n-lib.h>

#define MAIL_GETTEXT_PACKAGE "io.elementary.mail"
#define MAIL_LOCALEDIR "/nix/store/42g5ja5mmwzca76b48b20irqgf91sdxi-elementary-mail-7.0.0/shar" \
"e/locale"
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define MAIL_TYPE_APPLICATION (mail_application_get_type ())
#define MAIL_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MAIL_TYPE_APPLICATION, MailApplication))
#define MAIL_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MAIL_TYPE_APPLICATION, MailApplicationClass))
#define MAIL_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MAIL_TYPE_APPLICATION))
#define MAIL_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MAIL_TYPE_APPLICATION))
#define MAIL_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MAIL_TYPE_APPLICATION, MailApplicationClass))

typedef struct _MailApplication MailApplication;
typedef struct _MailApplicationClass MailApplicationClass;
typedef struct _MailApplicationPrivate MailApplicationPrivate;
enum  {
	MAIL_APPLICATION_0_PROPERTY,
	MAIL_APPLICATION_NUM_PROPERTIES
};
static GParamSpec* mail_application_properties[MAIL_APPLICATION_NUM_PROPERTIES];

#define MAIL_TYPE_MAIN_WINDOW (mail_main_window_get_type ())
#define MAIL_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MAIL_TYPE_MAIN_WINDOW, MailMainWindow))
#define MAIL_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MAIL_TYPE_MAIN_WINDOW, MailMainWindowClass))
#define MAIL_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MAIL_TYPE_MAIN_WINDOW))
#define MAIL_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MAIL_TYPE_MAIN_WINDOW))
#define MAIL_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MAIL_TYPE_MAIN_WINDOW, MailMainWindowClass))

typedef struct _MailMainWindow MailMainWindow;
typedef struct _MailMainWindowClass MailMainWindowClass;
typedef struct _Block1Data Block1Data;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block2Data Block2Data;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Block3Data Block3Data;
#define _g_uri_unref0(var) ((var == NULL) ? NULL : (var = (g_uri_unref (var), NULL)))

#define MAIL_TYPE_COMPOSER_WINDOW (mail_composer_window_get_type ())
#define MAIL_COMPOSER_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MAIL_TYPE_COMPOSER_WINDOW, MailComposerWindow))
#define MAIL_COMPOSER_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MAIL_TYPE_COMPOSER_WINDOW, MailComposerWindowClass))
#define MAIL_IS_COMPOSER_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MAIL_TYPE_COMPOSER_WINDOW))
#define MAIL_IS_COMPOSER_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MAIL_TYPE_COMPOSER_WINDOW))
#define MAIL_COMPOSER_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MAIL_TYPE_COMPOSER_WINDOW, MailComposerWindowClass))

typedef struct _MailComposerWindow MailComposerWindow;
typedef struct _MailComposerWindowClass MailComposerWindowClass;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define MAIL_TYPE_INBOX_MONITOR (mail_inbox_monitor_get_type ())
#define MAIL_INBOX_MONITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MAIL_TYPE_INBOX_MONITOR, MailInboxMonitor))
#define MAIL_INBOX_MONITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MAIL_TYPE_INBOX_MONITOR, MailInboxMonitorClass))
#define MAIL_IS_INBOX_MONITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MAIL_TYPE_INBOX_MONITOR))
#define MAIL_IS_INBOX_MONITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MAIL_TYPE_INBOX_MONITOR))
#define MAIL_INBOX_MONITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MAIL_TYPE_INBOX_MONITOR, MailInboxMonitorClass))

typedef struct _MailInboxMonitor MailInboxMonitor;
typedef struct _MailInboxMonitorClass MailInboxMonitorClass;
typedef struct _Block4Data Block4Data;

struct _MailApplication {
	GtkApplication parent_instance;
	MailApplicationPrivate * priv;
};

struct _MailApplicationClass {
	GtkApplicationClass parent_class;
};

struct _Block1Data {
	int _ref_count_;
	MailApplication* self;
	MailMainWindow* main_window;
};

struct _Block2Data {
	int _ref_count_;
	Block1Data * _data1_;
	gchar* to;
};

struct _Block3Data {
	int _ref_count_;
	Block2Data * _data2_;
	GUri* mailto;
};

struct _Block4Data {
	int _ref_count_;
	MailApplication* self;
	GraniteSettings* granite_settings;
	GtkSettings* gtk_settings;
};

static gpointer mail_application_parent_class = NULL;
VALA_EXTERN gboolean mail_application_run_in_background;
VALA_EXTERN GSettings* mail_application_settings;
GSettings* mail_application_settings = NULL;
gboolean mail_application_run_in_background = FALSE;

VALA_EXTERN GType mail_application_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (MailApplication, g_object_unref)
VALA_EXTERN MailApplication* mail_application_new (void);
VALA_EXTERN MailApplication* mail_application_construct (GType object_type);
static gint mail_application_real_command_line (GApplication* base,
                                         GApplicationCommandLine* command_line);
VALA_EXTERN GType mail_main_window_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (MailMainWindow, g_object_unref)
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static Block2Data* block2_data_ref (Block2Data* _data2_);
static void block2_data_unref (void * _userdata_);
static Block3Data* block3_data_ref (Block3Data* _data3_);
static void block3_data_unref (void * _userdata_);
VALA_EXTERN gboolean mail_main_window_get_is_session_started (MailMainWindow* self);
VALA_EXTERN MailComposerWindow* mail_composer_window_new (GtkWindow* parent,
                                              const gchar* to,
                                              const gchar* mailto_query);
VALA_EXTERN MailComposerWindow* mail_composer_window_construct (GType object_type,
                                                    GtkWindow* parent,
                                                    const gchar* to,
                                                    const gchar* mailto_query);
VALA_EXTERN GType mail_composer_window_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (MailComposerWindow, g_object_unref)
static void ______lambda112_ (Block3Data* _data3_);
static void _______lambda112__mail_main_window_session_started (MailMainWindow* _sender,
                                                         gpointer self);
static void mail_application_real_activate (GApplication* base);
VALA_EXTERN MailInboxMonitor* mail_inbox_monitor_new (void);
VALA_EXTERN MailInboxMonitor* mail_inbox_monitor_construct (GType object_type);
VALA_EXTERN GType mail_inbox_monitor_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (MailInboxMonitor, g_object_unref)
VALA_EXTERN void mail_inbox_monitor_start (MailInboxMonitor* self,
                               GAsyncReadyCallback _callback_,
                               gpointer _user_data_);
VALA_EXTERN void mail_inbox_monitor_start_finish (MailInboxMonitor* self,
                                      GAsyncResult* _res_);
static Block4Data* block4_data_ref (Block4Data* _data4_);
static void block4_data_unref (void * _userdata_);
VALA_EXTERN MailMainWindow* mail_main_window_new (GtkApplication* application);
VALA_EXTERN MailMainWindow* mail_main_window_construct (GType object_type,
                                            GtkApplication* application);
static void ___lambda111_ (Block4Data* _data4_);
static void ____lambda111__g_object_notify (GObject* _sender,
                                     GParamSpec* pspec,
                                     gpointer self);
static GObject * mail_application_constructor (GType type,
                                        guint n_construct_properties,
                                        GObjectConstructParam * construct_properties);
static void _mail_application___lambda113_ (MailApplication* self);
static void __mail_application___lambda113__g_simple_action_activate (GSimpleAction* _sender,
                                                               GVariant* parameter,
                                                               gpointer self);
static void mail_application_finalize (GObject * obj);
static GType mail_application_get_type_once (void);
static gint _vala_main (gchar** args,
                 gint args_length1);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);

static const GOptionEntry MAIL_APPLICATION_OPTIONS[2] = {{"background", 'b', (gint) 0, G_OPTION_ARG_NONE, &mail_application_run_in_background, "Run the Application in background", NULL}, {NULL}};

MailApplication*
mail_application_construct (GType object_type)
{
	MailApplication * self = NULL;
	self = (MailApplication*) g_object_new (object_type, "application-id", "io.elementary.mail", "flags", G_APPLICATION_HANDLES_COMMAND_LINE, NULL);
	return self;
}

MailApplication*
mail_application_new (void)
{
	return mail_application_construct (MAIL_TYPE_APPLICATION);
}

static Block1Data*
block1_data_ref (Block1Data* _data1_)
{
	g_atomic_int_inc (&_data1_->_ref_count_);
	return _data1_;
}

static void
block1_data_unref (void * _userdata_)
{
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
		MailApplication* self;
		self = _data1_->self;
		_g_object_unref0 (_data1_->main_window);
		_g_object_unref0 (self);
		g_slice_free (Block1Data, _data1_);
	}
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static Block2Data*
block2_data_ref (Block2Data* _data2_)
{
	g_atomic_int_inc (&_data2_->_ref_count_);
	return _data2_;
}

static void
block2_data_unref (void * _userdata_)
{
	Block2Data* _data2_;
	_data2_ = (Block2Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data2_->_ref_count_)) {
		MailApplication* self;
		self = _data2_->_data1_->self;
		_g_free0 (_data2_->to);
		block1_data_unref (_data2_->_data1_);
		_data2_->_data1_ = NULL;
		g_slice_free (Block2Data, _data2_);
	}
}

static Block3Data*
block3_data_ref (Block3Data* _data3_)
{
	g_atomic_int_inc (&_data3_->_ref_count_);
	return _data3_;
}

static void
block3_data_unref (void * _userdata_)
{
	Block3Data* _data3_;
	_data3_ = (Block3Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data3_->_ref_count_)) {
		MailApplication* self;
		self = _data3_->_data2_->_data1_->self;
		_g_uri_unref0 (_data3_->mailto);
		block2_data_unref (_data3_->_data2_);
		_data3_->_data2_ = NULL;
		g_slice_free (Block3Data, _data3_);
	}
}

static void
______lambda112_ (Block3Data* _data3_)
{
	Block2Data* _data2_;
	Block1Data* _data1_;
	MailApplication* self;
	MailMainWindow* _tmp0_;
	const gchar* _tmp1_;
	GUri* _tmp2_;
	const gchar* _tmp3_;
	MailComposerWindow* _tmp4_;
	MailComposerWindow* _tmp5_;
	_data2_ = _data3_->_data2_;
	_data1_ = _data2_->_data1_;
	self = _data1_->self;
	_tmp0_ = _data1_->main_window;
	_tmp1_ = _data2_->to;
	_tmp2_ = _data3_->mailto;
	_tmp3_ = g_uri_get_query (_tmp2_);
	_tmp4_ = mail_composer_window_new ((GtkWindow*) _tmp0_, _tmp1_, _tmp3_);
	g_object_ref_sink (_tmp4_);
	_tmp5_ = _tmp4_;
	gtk_widget_show_all ((GtkWidget*) _tmp5_);
	_g_object_unref0 (_tmp5_);
}

static void
_______lambda112__mail_main_window_session_started (MailMainWindow* _sender,
                                                    gpointer self)
{
	______lambda112_ (self);
}

static gint
mail_application_real_command_line (GApplication* base,
                                    GApplicationCommandLine* command_line)
{
	MailApplication * self;
	Block1Data* _data1_;
	gchar** argv = NULL;
	gint _tmp0_ = 0;
	gchar** _tmp1_;
	gint argv_length1;
	gint _argv_size_;
	GtkWindow* _tmp2_;
	GtkWindow* _tmp3_;
	MailMainWindow* _tmp4_;
	gchar** _tmp5_;
	gint _tmp5__length1;
	gchar** _tmp6_;
	gint _tmp6__length1;
	GError* _inner_error0_ = NULL;
	gint result;
	self = (MailApplication*) base;
	g_return_val_if_fail (command_line != NULL, 0);
	_data1_ = g_slice_new0 (Block1Data);
	_data1_->_ref_count_ = 1;
	_data1_->self = g_object_ref (self);
	g_application_activate ((GApplication*) self);
	_tmp1_ = g_application_command_line_get_arguments (command_line, &_tmp0_);
	argv = _tmp1_;
	argv_length1 = _tmp0_;
	_argv_size_ = argv_length1;
	_tmp2_ = gtk_application_get_active_window ((GtkApplication*) self);
	_tmp3_ = _tmp2_;
	_tmp4_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp3_, MAIL_TYPE_MAIN_WINDOW, MailMainWindow));
	_data1_->main_window = _tmp4_;
	_tmp5_ = argv;
	_tmp5__length1 = argv_length1;
	_tmp6_ = argv;
	_tmp6__length1 = argv_length1;
	{
		gchar** mailto_uri_collection = NULL;
		gint mailto_uri_collection_length1 = 0;
		gint _mailto_uri_collection_size_ = 0;
		gint mailto_uri_it = 0;
		mailto_uri_collection = _tmp5_ + 1;
		mailto_uri_collection_length1 = _tmp6__length1 - 1;
		for (mailto_uri_it = 0; mailto_uri_it < mailto_uri_collection_length1; mailto_uri_it = mailto_uri_it + 1) {
			gchar* _tmp7_;
			gchar* mailto_uri = NULL;
			_tmp7_ = g_strdup (mailto_uri_collection[mailto_uri_it]);
			mailto_uri = _tmp7_;
			{
				Block2Data* _data2_;
				_data2_ = g_slice_new0 (Block2Data);
				_data2_->_ref_count_ = 1;
				_data2_->_data1_ = block1_data_ref (_data1_);
				_data2_->to = NULL;
				{
					Block3Data* _data3_;
					GUri* _tmp14_;
					GUri* _tmp17_;
					const gchar* _tmp18_;
					GUri* _tmp21_;
					const gchar* _tmp22_;
					gchar* _tmp23_;
					MailMainWindow* _tmp24_;
					gboolean _tmp25_;
					gboolean _tmp26_;
					_data3_ = g_slice_new0 (Block3Data);
					_data3_->_ref_count_ = 1;
					_data3_->_data2_ = block2_data_ref (_data2_);
					_data3_->mailto = NULL;
					{
						GUri* _tmp8_ = NULL;
						const gchar* _tmp9_;
						GUri* _tmp10_;
						GUri* _tmp11_;
						_tmp9_ = mailto_uri;
						_tmp10_ = g_uri_parse (_tmp9_, G_URI_FLAGS_NONE, &_inner_error0_);
						_tmp8_ = _tmp10_;
						if (G_UNLIKELY (_inner_error0_ != NULL)) {
							goto __catch1_g_error;
						}
						_tmp11_ = _tmp8_;
						_tmp8_ = NULL;
						_g_uri_unref0 (_data3_->mailto);
						_data3_->mailto = _tmp11_;
						_g_uri_unref0 (_tmp8_);
					}
					goto __finally1;
					__catch1_g_error:
					{
						GError* _tmp12_;
						g_clear_error (&_inner_error0_);
						_tmp12_ = g_error_new_literal (G_OPTION_ERROR, G_OPTION_ERROR_BAD_VALUE, "Argument is not a URL.");
						_inner_error0_ = _tmp12_;
						goto __finally1;
					}
					__finally1:
					if (G_UNLIKELY (_inner_error0_ != NULL)) {
						gint _tmp13_ = -1;
						block3_data_unref (_data3_);
						_data3_ = NULL;
						if (_inner_error0_->domain == G_OPTION_ERROR) {
							goto __catch0_g_option_error;
						}
						_g_free0 (mailto_uri);
						block2_data_unref (_data2_);
						_data2_ = NULL;
						argv = (_vala_array_free (argv, argv_length1, (GDestroyNotify) g_free), NULL);
						block1_data_unref (_data1_);
						_data1_ = NULL;
						g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
						g_clear_error (&_inner_error0_);
						return _tmp13_;
					}
					_tmp14_ = _data3_->mailto;
					if (_tmp14_ == NULL) {
						GError* _tmp15_;
						gint _tmp16_ = -1;
						_tmp15_ = g_error_new_literal (G_OPTION_ERROR, G_OPTION_ERROR_BAD_VALUE, "Argument is not a URL.");
						_inner_error0_ = _tmp15_;
						block3_data_unref (_data3_);
						_data3_ = NULL;
						if (_inner_error0_->domain == G_OPTION_ERROR) {
							goto __catch0_g_option_error;
						}
						_g_free0 (mailto_uri);
						block2_data_unref (_data2_);
						_data2_ = NULL;
						argv = (_vala_array_free (argv, argv_length1, (GDestroyNotify) g_free), NULL);
						block1_data_unref (_data1_);
						_data1_ = NULL;
						g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
						g_clear_error (&_inner_error0_);
						return _tmp16_;
					}
					_tmp17_ = _data3_->mailto;
					_tmp18_ = g_uri_get_scheme (_tmp17_);
					if (g_strcmp0 (_tmp18_, "mailto") != 0) {
						GError* _tmp19_;
						gint _tmp20_ = -1;
						_tmp19_ = g_error_new_literal (G_OPTION_ERROR, G_OPTION_ERROR_BAD_VALUE, "Cannot open non-mailto: URL");
						_inner_error0_ = _tmp19_;
						block3_data_unref (_data3_);
						_data3_ = NULL;
						if (_inner_error0_->domain == G_OPTION_ERROR) {
							goto __catch0_g_option_error;
						}
						_g_free0 (mailto_uri);
						block2_data_unref (_data2_);
						_data2_ = NULL;
						argv = (_vala_array_free (argv, argv_length1, (GDestroyNotify) g_free), NULL);
						block1_data_unref (_data1_);
						_data1_ = NULL;
						g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
						g_clear_error (&_inner_error0_);
						return _tmp20_;
					}
					_tmp21_ = _data3_->mailto;
					_tmp22_ = g_uri_get_path (_tmp21_);
					_tmp23_ = g_uri_unescape_string (_tmp22_, NULL);
					_g_free0 (_data2_->to);
					_data2_->to = _tmp23_;
					_tmp24_ = _data1_->main_window;
					_tmp25_ = mail_main_window_get_is_session_started (_tmp24_);
					_tmp26_ = _tmp25_;
					if (_tmp26_) {
						MailMainWindow* _tmp27_;
						const gchar* _tmp28_;
						GUri* _tmp29_;
						const gchar* _tmp30_;
						MailComposerWindow* _tmp31_;
						MailComposerWindow* _tmp32_;
						_tmp27_ = _data1_->main_window;
						_tmp28_ = _data2_->to;
						_tmp29_ = _data3_->mailto;
						_tmp30_ = g_uri_get_query (_tmp29_);
						_tmp31_ = mail_composer_window_new ((GtkWindow*) _tmp27_, _tmp28_, _tmp30_);
						g_object_ref_sink (_tmp31_);
						_tmp32_ = _tmp31_;
						gtk_widget_show_all ((GtkWidget*) _tmp32_);
						_g_object_unref0 (_tmp32_);
					} else {
						MailMainWindow* _tmp33_;
						_tmp33_ = _data1_->main_window;
						g_signal_connect_data (_tmp33_, "session-started", (GCallback) _______lambda112__mail_main_window_session_started, block3_data_ref (_data3_), (GClosureNotify) block3_data_unref, 0);
					}
					block3_data_unref (_data3_);
					_data3_ = NULL;
				}
				goto __finally0;
				__catch0_g_option_error:
				{
					GError* e = NULL;
					GError* _tmp34_;
					const gchar* _tmp35_;
					e = _inner_error0_;
					_inner_error0_ = NULL;
					_tmp34_ = e;
					_tmp35_ = _tmp34_->message;
					g_warning ("Application.vala:118: Argument parsing error. %s", _tmp35_);
					_g_error_free0 (e);
				}
				__finally0:
				if (G_UNLIKELY (_inner_error0_ != NULL)) {
					gint _tmp36_ = -1;
					_g_free0 (mailto_uri);
					block2_data_unref (_data2_);
					_data2_ = NULL;
					argv = (_vala_array_free (argv, argv_length1, (GDestroyNotify) g_free), NULL);
					block1_data_unref (_data1_);
					_data1_ = NULL;
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
					g_clear_error (&_inner_error0_);
					return _tmp36_;
				}
				_g_free0 (mailto_uri);
				block2_data_unref (_data2_);
				_data2_ = NULL;
			}
		}
	}
	result = 0;
	argv = (_vala_array_free (argv, argv_length1, (GDestroyNotify) g_free), NULL);
	block1_data_unref (_data1_);
	_data1_ = NULL;
	return result;
}

static Block4Data*
block4_data_ref (Block4Data* _data4_)
{
	g_atomic_int_inc (&_data4_->_ref_count_);
	return _data4_;
}

static void
block4_data_unref (void * _userdata_)
{
	Block4Data* _data4_;
	_data4_ = (Block4Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data4_->_ref_count_)) {
		MailApplication* self;
		self = _data4_->self;
		_g_object_unref0 (_data4_->gtk_settings);
		_g_object_unref0 (_data4_->granite_settings);
		_g_object_unref0 (self);
		g_slice_free (Block4Data, _data4_);
	}
}

static void
___lambda111_ (Block4Data* _data4_)
{
	MailApplication* self;
	GtkSettings* _tmp0_;
	GraniteSettings* _tmp1_;
	GraniteSettingsColorScheme _tmp2_;
	GraniteSettingsColorScheme _tmp3_;
	self = _data4_->self;
	_tmp0_ = _data4_->gtk_settings;
	_tmp1_ = _data4_->granite_settings;
	_tmp2_ = granite_settings_get_prefers_color_scheme (_tmp1_);
	_tmp3_ = _tmp2_;
	g_object_set (_tmp0_, "gtk-application-prefer-dark-theme", _tmp3_ == GRANITE_SETTINGS_COLOR_SCHEME_DARK, NULL);
}

static void
____lambda111__g_object_notify (GObject* _sender,
                                GParamSpec* pspec,
                                gpointer self)
{
	___lambda111_ (self);
}

static void
mail_application_real_activate (GApplication* base)
{
	MailApplication * self;
	GtkWindow* _tmp2_;
	GtkWindow* _tmp3_;
	GtkWindow* _tmp33_;
	GtkWindow* _tmp34_;
	self = (MailApplication*) base;
	if (mail_application_run_in_background) {
		MailInboxMonitor* _tmp0_;
		MailInboxMonitor* _tmp1_;
		mail_application_run_in_background = FALSE;
		_tmp0_ = mail_inbox_monitor_new ();
		_tmp1_ = _tmp0_;
		mail_inbox_monitor_start (_tmp1_, NULL, NULL);
		_g_object_unref0 (_tmp1_);
		g_application_hold ((GApplication*) self);
		return;
	}
	_tmp2_ = gtk_application_get_active_window ((GtkApplication*) self);
	_tmp3_ = _tmp2_;
	if (_tmp3_ == NULL) {
		Block4Data* _data4_;
		GtkIconTheme* _tmp4_;
		MailMainWindow* main_window = NULL;
		MailMainWindow* _tmp5_;
		MailMainWindow* _tmp6_;
		gint window_x = 0;
		gint window_y = 0;
		GtkAllocation rect = {0};
		GSettings* _tmp7_;
		gint _tmp8_ = 0;
		gint _tmp9_ = 0;
		GSettings* _tmp10_;
		gint _tmp11_ = 0;
		gint _tmp12_ = 0;
		gboolean _tmp13_ = FALSE;
		MailMainWindow* _tmp15_;
		GtkAllocation _tmp16_;
		GSettings* _tmp17_;
		GraniteSettings* _tmp19_;
		GraniteSettings* _tmp20_;
		GtkSettings* _tmp21_;
		GtkSettings* _tmp22_;
		GtkSettings* _tmp23_;
		GraniteSettings* _tmp24_;
		GraniteSettingsColorScheme _tmp25_;
		GraniteSettingsColorScheme _tmp26_;
		GraniteSettings* _tmp27_;
		MailMainWindow* _tmp28_;
		GtkCssProvider* css_provider = NULL;
		GtkCssProvider* _tmp29_;
		GtkCssProvider* _tmp30_;
		GdkScreen* _tmp31_;
		GtkCssProvider* _tmp32_;
		_data4_ = g_slice_new0 (Block4Data);
		_data4_->_ref_count_ = 1;
		_data4_->self = g_object_ref (self);
		_tmp4_ = gtk_icon_theme_get_default ();
		gtk_icon_theme_add_resource_path (_tmp4_, "/io/elementary/mail");
		_tmp5_ = mail_main_window_new ((GtkApplication*) self);
		g_object_ref_sink (_tmp5_);
		main_window = _tmp5_;
		_tmp6_ = main_window;
		gtk_application_add_window ((GtkApplication*) self, (GtkWindow*) _tmp6_);
		memset (&rect, 0, sizeof (GtkAllocation));
		_tmp7_ = mail_application_settings;
		g_settings_get (_tmp7_, "window-position", "(ii)", &_tmp8_, &_tmp9_);
		window_x = _tmp8_;
		window_y = _tmp9_;
		_tmp10_ = mail_application_settings;
		g_settings_get (_tmp10_, "window-size", "(ii)", &_tmp11_, &_tmp12_);
		rect.width = _tmp11_;
		rect.height = _tmp12_;
		if (window_x != -1) {
			_tmp13_ = TRUE;
		} else {
			_tmp13_ = window_y != -1;
		}
		if (_tmp13_) {
			MailMainWindow* _tmp14_;
			_tmp14_ = main_window;
			gtk_window_move ((GtkWindow*) _tmp14_, window_x, window_y);
		}
		_tmp15_ = main_window;
		_tmp16_ = rect;
		gtk_widget_set_allocation ((GtkWidget*) _tmp15_, &_tmp16_);
		_tmp17_ = mail_application_settings;
		if (g_settings_get_boolean (_tmp17_, "window-maximized")) {
			MailMainWindow* _tmp18_;
			_tmp18_ = main_window;
			gtk_window_maximize ((GtkWindow*) _tmp18_);
		}
		_tmp19_ = granite_settings_get_default ();
		_tmp20_ = _g_object_ref0 (_tmp19_);
		_data4_->granite_settings = _tmp20_;
		_tmp21_ = gtk_settings_get_default ();
		_tmp22_ = _g_object_ref0 (_tmp21_);
		_data4_->gtk_settings = _tmp22_;
		_tmp23_ = _data4_->gtk_settings;
		_tmp24_ = _data4_->granite_settings;
		_tmp25_ = granite_settings_get_prefers_color_scheme (_tmp24_);
		_tmp26_ = _tmp25_;
		g_object_set (_tmp23_, "gtk-application-prefer-dark-theme", _tmp26_ == GRANITE_SETTINGS_COLOR_SCHEME_DARK, NULL);
		_tmp27_ = _data4_->granite_settings;
		g_signal_connect_data ((GObject*) _tmp27_, "notify::prefers-color-scheme", (GCallback) ____lambda111__g_object_notify, block4_data_ref (_data4_), (GClosureNotify) block4_data_unref, 0);
		_tmp28_ = main_window;
		gtk_widget_show_all ((GtkWidget*) _tmp28_);
		_tmp29_ = gtk_css_provider_new ();
		css_provider = _tmp29_;
		_tmp30_ = css_provider;
		gtk_css_provider_load_from_resource (_tmp30_, "io/elementary/mail/application.css");
		_tmp31_ = gdk_screen_get_default ();
		_tmp32_ = css_provider;
		gtk_style_context_add_provider_for_screen (_tmp31_, (GtkStyleProvider*) _tmp32_, (guint) GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
		_g_object_unref0 (css_provider);
		_g_object_unref0 (main_window);
		block4_data_unref (_data4_);
		_data4_ = NULL;
	}
	_tmp33_ = gtk_application_get_active_window ((GtkApplication*) self);
	_tmp34_ = _tmp33_;
	gtk_window_present (_tmp34_);
}

static void
_mail_application___lambda113_ (MailApplication* self)
{
	GtkWindow* _tmp0_;
	GtkWindow* _tmp1_;
	_tmp0_ = gtk_application_get_active_window ((GtkApplication*) self);
	_tmp1_ = _tmp0_;
	if (_tmp1_ != NULL) {
		GtkWindow* _tmp2_;
		GtkWindow* _tmp3_;
		_tmp2_ = gtk_application_get_active_window ((GtkApplication*) self);
		_tmp3_ = _tmp2_;
		gtk_widget_destroy ((GtkWidget*) _tmp3_);
	}
}

static void
__mail_application___lambda113__g_simple_action_activate (GSimpleAction* _sender,
                                                          GVariant* parameter,
                                                          gpointer self)
{
	_mail_application___lambda113_ ((MailApplication*) self);
}

static GObject *
mail_application_constructor (GType type,
                              guint n_construct_properties,
                              GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	MailApplication * self;
	GSimpleAction* quit_action = NULL;
	GSimpleAction* _tmp0_;
	GSimpleAction* _tmp1_;
	GSimpleAction* _tmp2_;
	gchar* _tmp3_;
	gchar** _tmp4_;
	gchar** _tmp5_;
	gint _tmp5__length1;
	parent_class = G_OBJECT_CLASS (mail_application_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MAIL_TYPE_APPLICATION, MailApplication);
	setlocale (LC_ALL, "");
	bindtextdomain (MAIL_GETTEXT_PACKAGE, MAIL_LOCALEDIR);
	bind_textdomain_codeset (MAIL_GETTEXT_PACKAGE, "UTF-8");
	textdomain (MAIL_GETTEXT_PACKAGE);
	g_application_add_main_option_entries ((GApplication*) self, MAIL_APPLICATION_OPTIONS);
	_tmp0_ = g_simple_action_new ("quit", NULL);
	quit_action = _tmp0_;
	_tmp1_ = quit_action;
	g_signal_connect_object (_tmp1_, "activate", (GCallback) __mail_application___lambda113__g_simple_action_activate, self, 0);
	_tmp2_ = quit_action;
	g_action_map_add_action ((GActionMap*) self, (GAction*) _tmp2_);
	_tmp3_ = g_strdup ("<Control>q");
	_tmp4_ = g_new0 (gchar*, 1 + 1);
	_tmp4_[0] = _tmp3_;
	_tmp5_ = _tmp4_;
	_tmp5__length1 = 1;
	gtk_application_set_accels_for_action ((GtkApplication*) self, "app.quit", _tmp5_);
	_tmp5_ = (_vala_array_free (_tmp5_, _tmp5__length1, (GDestroyNotify) g_free), NULL);
	_g_object_unref0 (quit_action);
	return obj;
}

static void
mail_application_class_init (MailApplicationClass * klass,
                             gpointer klass_data)
{
	GSettings* _tmp0_;
	mail_application_parent_class = g_type_class_peek_parent (klass);
	((GApplicationClass *) klass)->command_line = (gint (*) (GApplication*, GApplicationCommandLine*)) mail_application_real_command_line;
	((GApplicationClass *) klass)->activate = (void (*) (GApplication*)) mail_application_real_activate;
	G_OBJECT_CLASS (klass)->constructor = mail_application_constructor;
	G_OBJECT_CLASS (klass)->finalize = mail_application_finalize;
	_tmp0_ = g_settings_new ("io.elementary.mail");
	_g_object_unref0 (mail_application_settings);
	mail_application_settings = _tmp0_;
}

static void
mail_application_instance_init (MailApplication * self,
                                gpointer klass)
{
}

static void
mail_application_finalize (GObject * obj)
{
	MailApplication * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MAIL_TYPE_APPLICATION, MailApplication);
	G_OBJECT_CLASS (mail_application_parent_class)->finalize (obj);
}

static GType
mail_application_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (MailApplicationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) mail_application_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MailApplication), 0, (GInstanceInitFunc) mail_application_instance_init, NULL };
	GType mail_application_type_id;
	mail_application_type_id = g_type_register_static (gtk_application_get_type (), "MailApplication", &g_define_type_info, 0);
	return mail_application_type_id;
}

GType
mail_application_get_type (void)
{
	static volatile gsize mail_application_type_id__once = 0;
	if (g_once_init_enter (&mail_application_type_id__once)) {
		GType mail_application_type_id;
		mail_application_type_id = mail_application_get_type_once ();
		g_once_init_leave (&mail_application_type_id__once, mail_application_type_id);
	}
	return mail_application_type_id__once;
}

static gint
_vala_main (gchar** args,
            gint args_length1)
{
	MailApplication* application = NULL;
	MailApplication* _tmp0_;
	gint result;
	_tmp0_ = mail_application_new ();
	application = _tmp0_;
	result = g_application_run ((GApplication*) application, (gint) args_length1, args);
	_g_object_unref0 (application);
	return result;
}

int
main (int argc,
      char ** argv)
{
	return _vala_main (argv, argc);
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

