/* FolderSourceItem.c generated by valac 0.56.3, the Vala compiler
 * generated from FolderSourceItem.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: nil; tab-width: 4 -*-*/
/*-
 * Copyright (c) 2017 elementary LLC. (https://elementary.io)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 *
 * Authored by: Corentin Noël <corentin@elementary.io>
 */

#include <granite.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gtk/gtk.h>
#include <camel/camel.h>
#include <glib/gi18n-lib.h>
#include <gio/gio.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define MAIL_TYPE_FOLDER_SOURCE_ITEM (mail_folder_source_item_get_type ())
#define MAIL_FOLDER_SOURCE_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MAIL_TYPE_FOLDER_SOURCE_ITEM, MailFolderSourceItem))
#define MAIL_FOLDER_SOURCE_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MAIL_TYPE_FOLDER_SOURCE_ITEM, MailFolderSourceItemClass))
#define MAIL_IS_FOLDER_SOURCE_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MAIL_TYPE_FOLDER_SOURCE_ITEM))
#define MAIL_IS_FOLDER_SOURCE_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MAIL_TYPE_FOLDER_SOURCE_ITEM))
#define MAIL_FOLDER_SOURCE_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MAIL_TYPE_FOLDER_SOURCE_ITEM, MailFolderSourceItemClass))

typedef struct _MailFolderSourceItem MailFolderSourceItem;
typedef struct _MailFolderSourceItemClass MailFolderSourceItemClass;
typedef struct _MailFolderSourceItemPrivate MailFolderSourceItemPrivate;

#define MAIL_BACKEND_TYPE_ACCOUNT (mail_backend_account_get_type ())
#define MAIL_BACKEND_ACCOUNT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MAIL_BACKEND_TYPE_ACCOUNT, MailBackendAccount))
#define MAIL_BACKEND_ACCOUNT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MAIL_BACKEND_TYPE_ACCOUNT, MailBackendAccountClass))
#define MAIL_BACKEND_IS_ACCOUNT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MAIL_BACKEND_TYPE_ACCOUNT))
#define MAIL_BACKEND_IS_ACCOUNT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MAIL_BACKEND_TYPE_ACCOUNT))
#define MAIL_BACKEND_ACCOUNT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MAIL_BACKEND_TYPE_ACCOUNT, MailBackendAccountClass))

typedef struct _MailBackendAccount MailBackendAccount;
typedef struct _MailBackendAccountClass MailBackendAccountClass;
enum  {
	MAIL_FOLDER_SOURCE_ITEM_0_PROPERTY,
	MAIL_FOLDER_SOURCE_ITEM_ACCOUNT_PROPERTY,
	MAIL_FOLDER_SOURCE_ITEM_NUM_PROPERTIES
};
static GParamSpec* mail_folder_source_item_properties[MAIL_FOLDER_SOURCE_ITEM_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
enum  {
	MAIL_FOLDER_SOURCE_ITEM_REFRESH_SIGNAL,
	MAIL_FOLDER_SOURCE_ITEM_NUM_SIGNALS
};
static guint mail_folder_source_item_signals[MAIL_FOLDER_SOURCE_ITEM_NUM_SIGNALS] = {0};

struct _MailFolderSourceItem {
	GraniteWidgetsSourceListExpandableItem parent_instance;
	MailFolderSourceItemPrivate * priv;
	gchar* full_name;
};

struct _MailFolderSourceItemClass {
	GraniteWidgetsSourceListExpandableItemClass parent_class;
};

struct _MailFolderSourceItemPrivate {
	MailBackendAccount* _account;
	gboolean can_modify;
};

static gint MailFolderSourceItem_private_offset;
static gpointer mail_folder_source_item_parent_class = NULL;

VALA_EXTERN GType mail_folder_source_item_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (MailFolderSourceItem, g_object_unref)
VALA_EXTERN GType mail_backend_account_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (MailBackendAccount, g_object_unref)
VALA_EXTERN MailFolderSourceItem* mail_folder_source_item_new (MailBackendAccount* account,
                                                   CamelFolderInfo* folderinfo);
VALA_EXTERN MailFolderSourceItem* mail_folder_source_item_construct (GType object_type,
                                                         MailBackendAccount* account,
                                                         CamelFolderInfo* folderinfo);
VALA_EXTERN void mail_folder_source_item_update_infos (MailFolderSourceItem* self,
                                           CamelFolderInfo* folderinfo);
static GtkMenu* mail_folder_source_item_real_get_context_menu (GraniteWidgetsSourceListItem* base);
static void __lambda15_ (MailFolderSourceItem* self);
static void ___lambda15__gtk_menu_item_activate (GtkMenuItem* _sender,
                                          gpointer self);
VALA_EXTERN CamelFolderInfoFlags mail_utils_get_full_folder_info_flags (CamelService* service,
                                                            CamelFolderInfo* folderinfo);
VALA_EXTERN MailBackendAccount* mail_folder_source_item_get_account (MailFolderSourceItem* self);
VALA_EXTERN CamelService* mail_backend_account_get_service (MailBackendAccount* self);
static void mail_folder_source_item_set_account (MailFolderSourceItem* self,
                                          MailBackendAccount* value);
static void mail_folder_source_item_finalize (GObject * obj);
static GType mail_folder_source_item_get_type_once (void);
static void _vala_mail_folder_source_item_get_property (GObject * object,
                                                 guint property_id,
                                                 GValue * value,
                                                 GParamSpec * pspec);
static void _vala_mail_folder_source_item_set_property (GObject * object,
                                                 guint property_id,
                                                 const GValue * value,
                                                 GParamSpec * pspec);

static inline gpointer
mail_folder_source_item_get_instance_private (MailFolderSourceItem* self)
{
	return G_STRUCT_MEMBER_P (self, MailFolderSourceItem_private_offset);
}

MailFolderSourceItem*
mail_folder_source_item_construct (GType object_type,
                                   MailBackendAccount* account,
                                   CamelFolderInfo* folderinfo)
{
	MailFolderSourceItem * self = NULL;
	g_return_val_if_fail (account != NULL, NULL);
	g_return_val_if_fail (folderinfo != NULL, NULL);
	self = (MailFolderSourceItem*) g_object_new (object_type, "account", account, NULL);
	mail_folder_source_item_update_infos (self, folderinfo);
	return self;
}

MailFolderSourceItem*
mail_folder_source_item_new (MailBackendAccount* account,
                             CamelFolderInfo* folderinfo)
{
	return mail_folder_source_item_construct (MAIL_TYPE_FOLDER_SOURCE_ITEM, account, folderinfo);
}

static void
__lambda15_ (MailFolderSourceItem* self)
{
	g_signal_emit (self, mail_folder_source_item_signals[MAIL_FOLDER_SOURCE_ITEM_REFRESH_SIGNAL], 0);
}

static void
___lambda15__gtk_menu_item_activate (GtkMenuItem* _sender,
                                     gpointer self)
{
	__lambda15_ ((MailFolderSourceItem*) self);
}

static GtkMenu*
mail_folder_source_item_real_get_context_menu (GraniteWidgetsSourceListItem* base)
{
	MailFolderSourceItem * self;
	GtkMenu* menu = NULL;
	GtkMenu* _tmp0_;
	GtkMenuItem* refresh_item = NULL;
	GtkMenuItem* _tmp1_;
	GtkMenu* result;
	self = (MailFolderSourceItem*) base;
	_tmp0_ = (GtkMenu*) gtk_menu_new ();
	g_object_ref_sink (_tmp0_);
	menu = _tmp0_;
	_tmp1_ = (GtkMenuItem*) gtk_menu_item_new_with_label (_ ("Refresh folder"));
	g_object_ref_sink (_tmp1_);
	refresh_item = _tmp1_;
	gtk_container_add ((GtkContainer*) menu, (GtkWidget*) refresh_item);
	gtk_widget_show_all ((GtkWidget*) menu);
	g_signal_connect_object (refresh_item, "activate", (GCallback) ___lambda15__gtk_menu_item_activate, self, 0);
	result = menu;
	_g_object_unref0 (refresh_item);
	return result;
}

void
mail_folder_source_item_update_infos (MailFolderSourceItem* self,
                                      CamelFolderInfo* folderinfo)
{
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	CamelFolderInfoFlags full_folder_info_flags = 0U;
	MailBackendAccount* _tmp5_;
	CamelService* _tmp6_;
	CamelService* _tmp7_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (folderinfo != NULL);
	_tmp0_ = folderinfo->display_name;
	granite_widgets_source_list_item_set_name ((GraniteWidgetsSourceListItem*) self, _tmp0_);
	_tmp1_ = folderinfo->full_name;
	_tmp2_ = g_strdup (_tmp1_);
	_g_free0 (self->full_name);
	self->full_name = _tmp2_;
	if (folderinfo->unread > ((gint32) 0)) {
		gchar* _tmp3_;
		gchar* _tmp4_;
		_tmp3_ = g_strdup_printf ("%d", (gint) folderinfo->unread);
		_tmp4_ = _tmp3_;
		granite_widgets_source_list_item_set_badge ((GraniteWidgetsSourceListItem*) self, _tmp4_);
		_g_free0 (_tmp4_);
	}
	_tmp5_ = self->priv->_account;
	_tmp6_ = mail_backend_account_get_service (_tmp5_);
	_tmp7_ = _tmp6_;
	full_folder_info_flags = mail_utils_get_full_folder_info_flags (_tmp7_, folderinfo);
	switch (full_folder_info_flags & CAMEL_FOLDER_TYPE_MASK) {
		case CAMEL_FOLDER_TYPE_INBOX:
		{
			GThemedIcon* _tmp8_;
			GThemedIcon* _tmp9_;
			_tmp8_ = (GThemedIcon*) g_themed_icon_new ("mail-inbox");
			_tmp9_ = _tmp8_;
			granite_widgets_source_list_item_set_icon ((GraniteWidgetsSourceListItem*) self, (GIcon*) _tmp9_);
			_g_object_unref0 (_tmp9_);
			self->priv->can_modify = FALSE;
			break;
		}
		case CAMEL_FOLDER_TYPE_OUTBOX:
		{
			GThemedIcon* _tmp10_;
			GThemedIcon* _tmp11_;
			_tmp10_ = (GThemedIcon*) g_themed_icon_new ("mail-outbox");
			_tmp11_ = _tmp10_;
			granite_widgets_source_list_item_set_icon ((GraniteWidgetsSourceListItem*) self, (GIcon*) _tmp11_);
			_g_object_unref0 (_tmp11_);
			self->priv->can_modify = FALSE;
			break;
		}
		case CAMEL_FOLDER_TYPE_TRASH:
		{
			const gchar* _tmp12_ = NULL;
			GThemedIcon* _tmp13_;
			GThemedIcon* _tmp14_;
			if (folderinfo->total == ((gint32) 0)) {
				_tmp12_ = "user-trash";
			} else {
				_tmp12_ = "user-trash-full";
			}
			_tmp13_ = (GThemedIcon*) g_themed_icon_new (_tmp12_);
			_tmp14_ = _tmp13_;
			granite_widgets_source_list_item_set_icon ((GraniteWidgetsSourceListItem*) self, (GIcon*) _tmp14_);
			_g_object_unref0 (_tmp14_);
			self->priv->can_modify = FALSE;
			granite_widgets_source_list_item_set_badge ((GraniteWidgetsSourceListItem*) self, NULL);
			break;
		}
		case CAMEL_FOLDER_TYPE_JUNK:
		{
			GThemedIcon* _tmp15_;
			GThemedIcon* _tmp16_;
			_tmp15_ = (GThemedIcon*) g_themed_icon_new ("edit-flag");
			_tmp16_ = _tmp15_;
			granite_widgets_source_list_item_set_icon ((GraniteWidgetsSourceListItem*) self, (GIcon*) _tmp16_);
			_g_object_unref0 (_tmp16_);
			self->priv->can_modify = FALSE;
			break;
		}
		case CAMEL_FOLDER_TYPE_SENT:
		{
			GThemedIcon* _tmp17_;
			GThemedIcon* _tmp18_;
			_tmp17_ = (GThemedIcon*) g_themed_icon_new ("mail-sent");
			_tmp18_ = _tmp17_;
			granite_widgets_source_list_item_set_icon ((GraniteWidgetsSourceListItem*) self, (GIcon*) _tmp18_);
			_g_object_unref0 (_tmp18_);
			self->priv->can_modify = FALSE;
			break;
		}
		case CAMEL_FOLDER_TYPE_ARCHIVE:
		{
			GThemedIcon* _tmp19_;
			GThemedIcon* _tmp20_;
			_tmp19_ = (GThemedIcon*) g_themed_icon_new ("mail-archive");
			_tmp20_ = _tmp19_;
			granite_widgets_source_list_item_set_icon ((GraniteWidgetsSourceListItem*) self, (GIcon*) _tmp20_);
			_g_object_unref0 (_tmp20_);
			self->priv->can_modify = FALSE;
			granite_widgets_source_list_item_set_badge ((GraniteWidgetsSourceListItem*) self, NULL);
			break;
		}
		case CAMEL_FOLDER_TYPE_DRAFTS:
		{
			GThemedIcon* _tmp21_;
			GThemedIcon* _tmp22_;
			_tmp21_ = (GThemedIcon*) g_themed_icon_new ("mail-drafts");
			_tmp22_ = _tmp21_;
			granite_widgets_source_list_item_set_icon ((GraniteWidgetsSourceListItem*) self, (GIcon*) _tmp22_);
			_g_object_unref0 (_tmp22_);
			self->priv->can_modify = FALSE;
			break;
		}
		default:
		{
			GThemedIcon* _tmp23_;
			GThemedIcon* _tmp24_;
			_tmp23_ = (GThemedIcon*) g_themed_icon_new ("folder");
			_tmp24_ = _tmp23_;
			granite_widgets_source_list_item_set_icon ((GraniteWidgetsSourceListItem*) self, (GIcon*) _tmp24_);
			_g_object_unref0 (_tmp24_);
			self->priv->can_modify = TRUE;
			break;
		}
	}
}

MailBackendAccount*
mail_folder_source_item_get_account (MailFolderSourceItem* self)
{
	MailBackendAccount* result;
	MailBackendAccount* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_account;
	result = _tmp0_;
	return result;
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static void
mail_folder_source_item_set_account (MailFolderSourceItem* self,
                                     MailBackendAccount* value)
{
	MailBackendAccount* old_value;
	g_return_if_fail (self != NULL);
	old_value = mail_folder_source_item_get_account (self);
	if (old_value != value) {
		MailBackendAccount* _tmp0_;
		_tmp0_ = _g_object_ref0 (value);
		_g_object_unref0 (self->priv->_account);
		self->priv->_account = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, mail_folder_source_item_properties[MAIL_FOLDER_SOURCE_ITEM_ACCOUNT_PROPERTY]);
	}
}

static void
mail_folder_source_item_class_init (MailFolderSourceItemClass * klass,
                                    gpointer klass_data)
{
	mail_folder_source_item_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &MailFolderSourceItem_private_offset);
	((GraniteWidgetsSourceListItemClass *) klass)->get_context_menu = (GtkMenu* (*) (GraniteWidgetsSourceListItem*)) mail_folder_source_item_real_get_context_menu;
	G_OBJECT_CLASS (klass)->get_property = _vala_mail_folder_source_item_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_mail_folder_source_item_set_property;
	G_OBJECT_CLASS (klass)->finalize = mail_folder_source_item_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), MAIL_FOLDER_SOURCE_ITEM_ACCOUNT_PROPERTY, mail_folder_source_item_properties[MAIL_FOLDER_SOURCE_ITEM_ACCOUNT_PROPERTY] = g_param_spec_object ("account", "account", "account", MAIL_BACKEND_TYPE_ACCOUNT, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
	mail_folder_source_item_signals[MAIL_FOLDER_SOURCE_ITEM_REFRESH_SIGNAL] = g_signal_new ("refresh", MAIL_TYPE_FOLDER_SOURCE_ITEM, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}

static void
mail_folder_source_item_instance_init (MailFolderSourceItem * self,
                                       gpointer klass)
{
	self->priv = mail_folder_source_item_get_instance_private (self);
	self->priv->can_modify = TRUE;
}

static void
mail_folder_source_item_finalize (GObject * obj)
{
	MailFolderSourceItem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MAIL_TYPE_FOLDER_SOURCE_ITEM, MailFolderSourceItem);
	_g_free0 (self->full_name);
	_g_object_unref0 (self->priv->_account);
	G_OBJECT_CLASS (mail_folder_source_item_parent_class)->finalize (obj);
}

static GType
mail_folder_source_item_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (MailFolderSourceItemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) mail_folder_source_item_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MailFolderSourceItem), 0, (GInstanceInitFunc) mail_folder_source_item_instance_init, NULL };
	GType mail_folder_source_item_type_id;
	mail_folder_source_item_type_id = g_type_register_static (GRANITE_WIDGETS_SOURCE_LIST_TYPE_EXPANDABLE_ITEM, "MailFolderSourceItem", &g_define_type_info, 0);
	MailFolderSourceItem_private_offset = g_type_add_instance_private (mail_folder_source_item_type_id, sizeof (MailFolderSourceItemPrivate));
	return mail_folder_source_item_type_id;
}

GType
mail_folder_source_item_get_type (void)
{
	static volatile gsize mail_folder_source_item_type_id__once = 0;
	if (g_once_init_enter (&mail_folder_source_item_type_id__once)) {
		GType mail_folder_source_item_type_id;
		mail_folder_source_item_type_id = mail_folder_source_item_get_type_once ();
		g_once_init_leave (&mail_folder_source_item_type_id__once, mail_folder_source_item_type_id);
	}
	return mail_folder_source_item_type_id__once;
}

static void
_vala_mail_folder_source_item_get_property (GObject * object,
                                            guint property_id,
                                            GValue * value,
                                            GParamSpec * pspec)
{
	MailFolderSourceItem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, MAIL_TYPE_FOLDER_SOURCE_ITEM, MailFolderSourceItem);
	switch (property_id) {
		case MAIL_FOLDER_SOURCE_ITEM_ACCOUNT_PROPERTY:
		g_value_set_object (value, mail_folder_source_item_get_account (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_mail_folder_source_item_set_property (GObject * object,
                                            guint property_id,
                                            const GValue * value,
                                            GParamSpec * pspec)
{
	MailFolderSourceItem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, MAIL_TYPE_FOLDER_SOURCE_ITEM, MailFolderSourceItem);
	switch (property_id) {
		case MAIL_FOLDER_SOURCE_ITEM_ACCOUNT_PROPERTY:
		mail_folder_source_item_set_account (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

