/* ComposerWindow.c generated by valac 0.56.3, the Vala compiler
 * generated from ComposerWindow.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: nil; tab-width: 4 -*-*/
/*-
 * Copyright (c) 2017 elementary LLC. (https://elementary.io)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authored by: David Hewitt <davidmhewitt@gmail.com>
 */

#include <handy.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <glib/gi18n-lib.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define MAIL_TYPE_COMPOSER_WINDOW (mail_composer_window_get_type ())
#define MAIL_COMPOSER_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MAIL_TYPE_COMPOSER_WINDOW, MailComposerWindow))
#define MAIL_COMPOSER_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MAIL_TYPE_COMPOSER_WINDOW, MailComposerWindowClass))
#define MAIL_IS_COMPOSER_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MAIL_TYPE_COMPOSER_WINDOW))
#define MAIL_IS_COMPOSER_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MAIL_TYPE_COMPOSER_WINDOW))
#define MAIL_COMPOSER_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MAIL_TYPE_COMPOSER_WINDOW, MailComposerWindowClass))

typedef struct _MailComposerWindow MailComposerWindow;
typedef struct _MailComposerWindowClass MailComposerWindowClass;
typedef struct _MailComposerWindowPrivate MailComposerWindowPrivate;

#define MAIL_TYPE_COMPOSER_WIDGET (mail_composer_widget_get_type ())
#define MAIL_COMPOSER_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MAIL_TYPE_COMPOSER_WIDGET, MailComposerWidget))
#define MAIL_COMPOSER_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MAIL_TYPE_COMPOSER_WIDGET, MailComposerWidgetClass))
#define MAIL_IS_COMPOSER_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MAIL_TYPE_COMPOSER_WIDGET))
#define MAIL_IS_COMPOSER_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MAIL_TYPE_COMPOSER_WIDGET))
#define MAIL_COMPOSER_WIDGET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MAIL_TYPE_COMPOSER_WIDGET, MailComposerWidgetClass))

typedef struct _MailComposerWidget MailComposerWidget;
typedef struct _MailComposerWidgetClass MailComposerWidgetClass;
enum  {
	MAIL_COMPOSER_WINDOW_0_PROPERTY,
	MAIL_COMPOSER_WINDOW_COMPOSER_WIDGET_PROPERTY,
	MAIL_COMPOSER_WINDOW_NUM_PROPERTIES
};
static GParamSpec* mail_composer_window_properties[MAIL_COMPOSER_WINDOW_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block19Data Block19Data;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _MailComposerWindow {
	HdyApplicationWindow parent_instance;
	MailComposerWindowPrivate * priv;
};

struct _MailComposerWindowClass {
	HdyApplicationWindowClass parent_class;
};

struct _MailComposerWindowPrivate {
	MailComposerWidget* _composer_widget;
};

struct _Block19Data {
	int _ref_count_;
	MailComposerWindow* self;
	HdyHeaderBar* titlebar;
};

static gint MailComposerWindow_private_offset;
static gpointer mail_composer_window_parent_class = NULL;

VALA_EXTERN GType mail_composer_window_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (MailComposerWindow, g_object_unref)
VALA_EXTERN GType mail_composer_widget_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (MailComposerWidget, g_object_unref)
VALA_EXTERN MailComposerWindow* mail_composer_window_new (GtkWindow* parent,
                                              const gchar* to,
                                              const gchar* mailto_query);
VALA_EXTERN MailComposerWindow* mail_composer_window_construct (GType object_type,
                                                    GtkWindow* parent,
                                                    const gchar* to,
                                                    const gchar* mailto_query);
VALA_EXTERN MailComposerWidget* mail_composer_widget_new_with_headers (const gchar* to,
                                                           const gchar* mailto_query);
VALA_EXTERN MailComposerWidget* mail_composer_widget_construct_with_headers (GType object_type,
                                                                 const gchar* to,
                                                                 const gchar* mailto_query);
VALA_EXTERN MailComposerWindow* mail_composer_window_new_for_widget (GtkWindow* parent,
                                                         MailComposerWidget* composer_widget);
VALA_EXTERN MailComposerWindow* mail_composer_window_construct_for_widget (GType object_type,
                                                               GtkWindow* parent,
                                                               MailComposerWidget* composer_widget);
VALA_EXTERN MailComposerWidget* mail_composer_window_get_composer_widget (MailComposerWindow* self);
static void mail_composer_window_set_composer_widget (MailComposerWindow* self,
                                               MailComposerWidget* value);
static GObject * mail_composer_window_constructor (GType type,
                                            guint n_construct_properties,
                                            GObjectConstructParam * construct_properties);
static Block19Data* block19_data_ref (Block19Data* _data19_);
static void block19_data_unref (void * _userdata_);
static void _mail_composer_window___lambda64_ (MailComposerWindow* self);
static void __mail_composer_window___lambda64__mail_composer_widget_discarded (MailComposerWidget* _sender,
                                                                        gpointer self);
static void _mail_composer_window___lambda65_ (MailComposerWindow* self);
static void __mail_composer_window___lambda65__mail_composer_widget_sent (MailComposerWidget* _sender,
                                                                   gpointer self);
static void _mail_composer_window___lambda66_ (Block19Data* _data19_,
                                        const gchar* subject);
static void __mail_composer_window___lambda66__mail_composer_widget_subject_changed (MailComposerWidget* _sender,
                                                                              const gchar* subject,
                                                                              gpointer self);
static void mail_composer_window_finalize (GObject * obj);
static GType mail_composer_window_get_type_once (void);
static void _vala_mail_composer_window_get_property (GObject * object,
                                              guint property_id,
                                              GValue * value,
                                              GParamSpec * pspec);
static void _vala_mail_composer_window_set_property (GObject * object,
                                              guint property_id,
                                              const GValue * value,
                                              GParamSpec * pspec);

static inline gpointer
mail_composer_window_get_instance_private (MailComposerWindow* self)
{
	return G_STRUCT_MEMBER_P (self, MailComposerWindow_private_offset);
}

MailComposerWindow*
mail_composer_window_construct (GType object_type,
                                GtkWindow* parent,
                                const gchar* to,
                                const gchar* mailto_query)
{
	MailComposerWindow * self = NULL;
	MailComposerWidget* _tmp0_;
	MailComposerWidget* _tmp1_;
	g_return_val_if_fail (parent != NULL, NULL);
	_tmp0_ = mail_composer_widget_new_with_headers (to, mailto_query);
	g_object_ref_sink (_tmp0_);
	_tmp1_ = _tmp0_;
	self = (MailComposerWindow*) g_object_new (object_type, "transient-for", parent, "composer-widget", _tmp1_, NULL);
	_g_object_unref0 (_tmp1_);
	return self;
}

MailComposerWindow*
mail_composer_window_new (GtkWindow* parent,
                          const gchar* to,
                          const gchar* mailto_query)
{
	return mail_composer_window_construct (MAIL_TYPE_COMPOSER_WINDOW, parent, to, mailto_query);
}

MailComposerWindow*
mail_composer_window_construct_for_widget (GType object_type,
                                           GtkWindow* parent,
                                           MailComposerWidget* composer_widget)
{
	MailComposerWindow * self = NULL;
	g_return_val_if_fail (parent != NULL, NULL);
	g_return_val_if_fail (composer_widget != NULL, NULL);
	self = (MailComposerWindow*) g_object_new (object_type, "transient-for", parent, "composer-widget", composer_widget, NULL);
	return self;
}

MailComposerWindow*
mail_composer_window_new_for_widget (GtkWindow* parent,
                                     MailComposerWidget* composer_widget)
{
	return mail_composer_window_construct_for_widget (MAIL_TYPE_COMPOSER_WINDOW, parent, composer_widget);
}

MailComposerWidget*
mail_composer_window_get_composer_widget (MailComposerWindow* self)
{
	MailComposerWidget* result;
	MailComposerWidget* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_composer_widget;
	result = _tmp0_;
	return result;
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static void
mail_composer_window_set_composer_widget (MailComposerWindow* self,
                                          MailComposerWidget* value)
{
	MailComposerWidget* old_value;
	g_return_if_fail (self != NULL);
	old_value = mail_composer_window_get_composer_widget (self);
	if (old_value != value) {
		MailComposerWidget* _tmp0_;
		_tmp0_ = _g_object_ref0 (value);
		_g_object_unref0 (self->priv->_composer_widget);
		self->priv->_composer_widget = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, mail_composer_window_properties[MAIL_COMPOSER_WINDOW_COMPOSER_WIDGET_PROPERTY]);
	}
}

static Block19Data*
block19_data_ref (Block19Data* _data19_)
{
	g_atomic_int_inc (&_data19_->_ref_count_);
	return _data19_;
}

static void
block19_data_unref (void * _userdata_)
{
	Block19Data* _data19_;
	_data19_ = (Block19Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data19_->_ref_count_)) {
		MailComposerWindow* self;
		self = _data19_->self;
		_g_object_unref0 (_data19_->titlebar);
		_g_object_unref0 (self);
		g_slice_free (Block19Data, _data19_);
	}
}

static void
_mail_composer_window___lambda64_ (MailComposerWindow* self)
{
	gtk_window_close ((GtkWindow*) self);
}

static void
__mail_composer_window___lambda64__mail_composer_widget_discarded (MailComposerWidget* _sender,
                                                                   gpointer self)
{
	_mail_composer_window___lambda64_ ((MailComposerWindow*) self);
}

static void
_mail_composer_window___lambda65_ (MailComposerWindow* self)
{
	gtk_window_close ((GtkWindow*) self);
}

static void
__mail_composer_window___lambda65__mail_composer_widget_sent (MailComposerWidget* _sender,
                                                              gpointer self)
{
	_mail_composer_window___lambda65_ ((MailComposerWindow*) self);
}

static void
_mail_composer_window___lambda66_ (Block19Data* _data19_,
                                   const gchar* subject)
{
	MailComposerWindow* self;
	gboolean _tmp0_ = FALSE;
	HdyHeaderBar* _tmp3_;
	self = _data19_->self;
	if (subject == NULL) {
		_tmp0_ = TRUE;
	} else {
		gint _tmp1_;
		gint _tmp2_;
		_tmp1_ = strlen (subject);
		_tmp2_ = _tmp1_;
		_tmp0_ = _tmp2_ == 0;
	}
	if (_tmp0_) {
		subject = _ ("New Message");
	}
	_tmp3_ = _data19_->titlebar;
	gtk_window_set_title ((GtkWindow*) self, subject);
	hdy_header_bar_set_title (_tmp3_, subject);
}

static void
__mail_composer_window___lambda66__mail_composer_widget_subject_changed (MailComposerWidget* _sender,
                                                                         const gchar* subject,
                                                                         gpointer self)
{
	_mail_composer_window___lambda66_ (self, subject);
}

static GObject *
mail_composer_window_constructor (GType type,
                                  guint n_construct_properties,
                                  GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	MailComposerWindow * self;
	Block19Data* _data19_;
	gchar* _tmp0_;
	HdyHeaderBar* _tmp1_ = NULL;
	HdyHeaderBar* _tmp2_;
	GtkStyleContext* _tmp3_;
	MailComposerWidget* _tmp4_;
	MailComposerWidget* _tmp5_;
	MailComposerWidget* _tmp6_;
	GtkGrid* content_grid = NULL;
	GtkGrid* _tmp7_;
	GtkGrid* _tmp8_;
	GtkGrid* _tmp9_;
	HdyHeaderBar* _tmp10_;
	GtkGrid* _tmp11_;
	MailComposerWidget* _tmp12_;
	GtkGrid* _tmp13_;
	parent_class = G_OBJECT_CLASS (mail_composer_window_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MAIL_TYPE_COMPOSER_WINDOW, MailComposerWindow);
	_data19_ = g_slice_new0 (Block19Data);
	_data19_->_ref_count_ = 1;
	_data19_->self = g_object_ref (self);
	_tmp0_ = g_strdup (_ ("New Message"));
	_tmp1_ = (HdyHeaderBar*) hdy_header_bar_new ();
	hdy_header_bar_set_has_subtitle (_tmp1_, FALSE);
	hdy_header_bar_set_show_close_button (_tmp1_, TRUE);
	hdy_header_bar_set_title (_tmp1_, _tmp0_);
	_g_free0 (_tmp0_);
	g_object_ref_sink (_tmp1_);
	_data19_->titlebar = _tmp1_;
	_tmp2_ = _data19_->titlebar;
	_tmp3_ = gtk_widget_get_style_context ((GtkWidget*) _tmp2_);
	gtk_style_context_add_class (_tmp3_, "default-decoration");
	_tmp4_ = self->priv->_composer_widget;
	g_signal_connect_object (_tmp4_, "discarded", (GCallback) __mail_composer_window___lambda64__mail_composer_widget_discarded, self, 0);
	_tmp5_ = self->priv->_composer_widget;
	g_signal_connect_object (_tmp5_, "sent", (GCallback) __mail_composer_window___lambda65__mail_composer_widget_sent, self, 0);
	_tmp6_ = self->priv->_composer_widget;
	g_signal_connect_data (_tmp6_, "subject-changed", (GCallback) __mail_composer_window___lambda66__mail_composer_widget_subject_changed, block19_data_ref (_data19_), (GClosureNotify) block19_data_unref, 0);
	_tmp7_ = (GtkGrid*) gtk_grid_new ();
	g_object_ref_sink (_tmp7_);
	content_grid = _tmp7_;
	_tmp8_ = content_grid;
	gtk_orientable_set_orientation ((GtkOrientable*) _tmp8_, GTK_ORIENTATION_VERTICAL);
	_tmp9_ = content_grid;
	_tmp10_ = _data19_->titlebar;
	gtk_container_add ((GtkContainer*) _tmp9_, (GtkWidget*) _tmp10_);
	_tmp11_ = content_grid;
	_tmp12_ = self->priv->_composer_widget;
	gtk_container_add ((GtkContainer*) _tmp11_, (GtkWidget*) _tmp12_);
	g_object_set ((GtkWidget*) self, "height-request", 600, NULL);
	g_object_set ((GtkWidget*) self, "width-request", 680, NULL);
	gtk_window_set_title ((GtkWindow*) self, _ ("New Message"));
	g_object_set ((GtkWindow*) self, "window-position", GTK_WIN_POS_CENTER_ON_PARENT, NULL);
	_tmp13_ = content_grid;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp13_);
	_g_object_unref0 (content_grid);
	block19_data_unref (_data19_);
	_data19_ = NULL;
	return obj;
}

static void
mail_composer_window_class_init (MailComposerWindowClass * klass,
                                 gpointer klass_data)
{
	mail_composer_window_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &MailComposerWindow_private_offset);
	G_OBJECT_CLASS (klass)->get_property = _vala_mail_composer_window_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_mail_composer_window_set_property;
	G_OBJECT_CLASS (klass)->constructor = mail_composer_window_constructor;
	G_OBJECT_CLASS (klass)->finalize = mail_composer_window_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), MAIL_COMPOSER_WINDOW_COMPOSER_WIDGET_PROPERTY, mail_composer_window_properties[MAIL_COMPOSER_WINDOW_COMPOSER_WIDGET_PROPERTY] = g_param_spec_object ("composer-widget", "composer-widget", "composer-widget", MAIL_TYPE_COMPOSER_WIDGET, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
}

static void
mail_composer_window_instance_init (MailComposerWindow * self,
                                    gpointer klass)
{
	self->priv = mail_composer_window_get_instance_private (self);
}

static void
mail_composer_window_finalize (GObject * obj)
{
	MailComposerWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, MAIL_TYPE_COMPOSER_WINDOW, MailComposerWindow);
	_g_object_unref0 (self->priv->_composer_widget);
	G_OBJECT_CLASS (mail_composer_window_parent_class)->finalize (obj);
}

static GType
mail_composer_window_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (MailComposerWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) mail_composer_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MailComposerWindow), 0, (GInstanceInitFunc) mail_composer_window_instance_init, NULL };
	GType mail_composer_window_type_id;
	mail_composer_window_type_id = g_type_register_static (hdy_application_window_get_type (), "MailComposerWindow", &g_define_type_info, 0);
	MailComposerWindow_private_offset = g_type_add_instance_private (mail_composer_window_type_id, sizeof (MailComposerWindowPrivate));
	return mail_composer_window_type_id;
}

GType
mail_composer_window_get_type (void)
{
	static volatile gsize mail_composer_window_type_id__once = 0;
	if (g_once_init_enter (&mail_composer_window_type_id__once)) {
		GType mail_composer_window_type_id;
		mail_composer_window_type_id = mail_composer_window_get_type_once ();
		g_once_init_leave (&mail_composer_window_type_id__once, mail_composer_window_type_id);
	}
	return mail_composer_window_type_id__once;
}

static void
_vala_mail_composer_window_get_property (GObject * object,
                                         guint property_id,
                                         GValue * value,
                                         GParamSpec * pspec)
{
	MailComposerWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, MAIL_TYPE_COMPOSER_WINDOW, MailComposerWindow);
	switch (property_id) {
		case MAIL_COMPOSER_WINDOW_COMPOSER_WIDGET_PROPERTY:
		g_value_set_object (value, mail_composer_window_get_composer_widget (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_mail_composer_window_set_property (GObject * object,
                                         guint property_id,
                                         const GValue * value,
                                         GParamSpec * pspec)
{
	MailComposerWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, MAIL_TYPE_COMPOSER_WINDOW, MailComposerWindow);
	switch (property_id) {
		case MAIL_COMPOSER_WINDOW_COMPOSER_WIDGET_PROPERTY:
		mail_composer_window_set_composer_widget (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

